### ISSUE TITLE
My Project: Project Description should be moved little up and aligned || Alpha Testing

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-web#1000]
Env: http://www.code4socialgood.org
1.Login as Volunteer user.
2. Go to My project.
3. Click on applied project link.

Actual Result: The project description and alignment should be corrected. Pplease see screenshot for more details.
![myproject](https://user-images.githubusercontent.com/29553195/28853914-bf7b01b2-7701-11e7-9305-96bfb51a7cf3.jpg)

**Comment by Code4SocialGood** [comment]
This issue is duplicate with issue #929 . Close this issue and keep #929 open.
