### ISSUE TITLE
Slack Invitation - slackin

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#101]
Could you check if we could setup this tool: https://github.com/rauchg/slackin

If we use this tool for our Slack invitation, we could avoid calling the following web APIs from Java backend:
- Send out email invitation
- Check whether a user is registered in Slack

We could also avoid the potential issue below (we experienced this issue with our slack team site):
https://get.slack.help/hc/en-us/articles/201330256-Invite-new-members-to-your-Slack-team
_Slack may limit a team's ability to send more invitations if a large number has been sent but very few have been accepted._

It doesn't seem Gitter provides calling function. Slack provides both calling and video options. This is an advantage of Slack. We could use calling feature for the interview process when volunteer applies for a project. Otherwise web sites usually provide Uber Conference to facilitate interviews. There are limitation of Slack's free account, I will apply for a company account as nonprofit later.

**Comment by russon77** [comment]
i setup slackin with a free tier heroku app. we now can include it in a few ways

https://github.com/rauchg/slackin

- https://thawing-sierra-44739.herokuapp.com/badge.svg
  - maybe for the github readme?
- https://thawing-sierra-44739.herokuapp.com/
  - this is supposed to be placed in a  `<iframe>` if i understand

**Comment by russon77** [comment]
## plan

- [ ] update https://thawing-sierra-44739.herokuapp.com/ dns to have nice url, i.e. `join-our-slack.code4...`
- [ ] update footer link to open `join-our-slack.code4...` link in new tab
