### ISSUE TITLE
Volunteers page: organization users are displayed in this list

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1031]
Click Volunteers: this list should be volunteers only
However, some organization users are shown. See screen shot.
The backend is validate, it returns the correct result: GET /api/users/search

![image](https://user-images.githubusercontent.com/24813620/28957550-e7e9282e-78b7-11e7-914c-ad391822868b.png)

![image](https://user-images.githubusercontent.com/24813620/28957530-d57408f8-78b7-11e7-87e6-e8b730b2d30c.png)

![image](https://user-images.githubusercontent.com/24813620/28957637-59784e02-78b8-11e7-8d28-182b27766e58.png)

**Comment by webdev-burd** [comment]
The user view template specifies that at the top:
```html
<div class="page-title"  *ngIf="user">
  <h1 *ngIf="user.role === 'V'">Volunteer</h1>
  <h1 *ngIf="user.role === 'O'">Organization User</h1>
  <h1 *ngIf="user.role === 'A'">Admin User</h1>
</div>
```

**Comment by Code4SocialGood** [comment]
When you click Volunteers, you should get a list of only volunteers. Those organization users shouldn't show up on the list.

**Comment by Code4SocialGood** [comment]
PR #1097 has addressed this issue. We will retest this issue after refresh Dev with Prod data, and close the issue after retest.

**Comment by Code4SocialGood** [comment]
Issue Resolved.
