### ISSUE TITLE
Main Screen: Scrolling Message Not Centered

### ISSUE THREAD

**Issue by bshores** [Code4SocialGood/c4sg-web#1034]
**Description:**
The Welcome Splash screen when a user navigates to https://app.code4socialgood.org (And Dev) Is not centered over the project keyword search. 

**Assumptions:**
None

**Test Case:**
1. Navigate to the home landing page
"http://dev.code4socialgood.org"

**Expected Result:**
Scrolling text and welcome messaging should be centered over the project search welcome box

**Actual Result:**
See Screenshot. The text is justified up and to the left
![screen shot 2017-08-06 at 11 19 38 am](https://user-images.githubusercontent.com/29845297/29005458-313826c8-7a99-11e7-81f2-4beaf954c146.png)

**Comment by Code4SocialGood** [comment]
@bshores Which browser it is?

Here is how the home page displays in Chrome and IE (v11):

![image](https://user-images.githubusercontent.com/24813620/29005589-e50820ea-7aa3-11e7-8dbf-273b152088e6.png)

![image](https://user-images.githubusercontent.com/24813620/29005597-ff0f553a-7aa3-11e7-995f-10e57f9acbe5.png)

**Comment by bshores** [comment]
Wow. Strange. I am using chrome and see the same thing in safari. I am using an iMac 27” with a dell 4k second display. Maybe it is the setup for widescreen. Do we have an optimal resolution?

**Comment by Code4SocialGood** [comment]
No we don't have an optional resolution. Could you suggest which usually optional resolution is set, and  where could we find some well know guideline on user interface responsive design and testing?

**Comment by Code4SocialGood** [comment]
This issue will be reviewed during responsive design.
