### ISSUE TITLE
Auth - Admin User - Entitlement

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#114]
- **Current Menu**
My Account
My Projects

- **Change to**
My Account
Create Project
Create Organization

- **Reference**

![image](https://cloud.githubusercontent.com/assets/24813620/24132862/a206c3fe-0dc6-11e7-8273-f35098cf52ff.png)

**Comment by jekcosty** [comment]
This issue was created due to an unnecessary role qualification for an admin specifically C4SG_ADMIN. We do not expect more than 1 type of an admin so why qualify???

The changes will then have to be done on the front-end and back-end
