### ISSUE TITLE
Home Page - Add more padding to featured projects

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1157]
Add the more padding to the left and right, so they are not too close to the page edge
Use the same padding size as Volunteer/Organization section

![image](https://user-images.githubusercontent.com/24813620/29752115-9e133d7a-8b1d-11e7-8d65-4f6b6a770600.png)

![image](https://user-images.githubusercontent.com/24813620/29752127-ccd37300-8b1d-11e7-888c-942b92a1359d.png)

**Comment by tlgreg86** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by Code4SocialGood** [comment]
@tlgreg86 Issue is resolve in PR #1190. Great job!
