### ISSUE TITLE
Add information icon

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1171]
Login as volunteer user:  testvolunteeruser2@gmail.com / Opensource5social!
Click My Settings
On "C4SG Slack Username" text field, add an information icon next to the label. Otherwise, user will not know there is information unless they mouse over the field.

![image](https://user-images.githubusercontent.com/24813620/29834631-157df114-8cb5-11e7-95f4-c1fe4f3bd903.png)

![image](https://user-images.githubusercontent.com/24813620/29834694-3b8739ec-8cb5-11e7-9a6d-f59c1cec3db6.png)

**Comment by felipealves-gnu** [comment]
@Code4SocialGood what's the message do you need when the mouve over event happen ?

**Comment by Code4SocialGood** [comment]
@felipealves-gnu 
1. The tooltip is already there. Please add an **"information icon"** next to "C4SG Slack Username"
2. Please change the color from orange to some grey color. Orange is too bright.

![image](https://user-images.githubusercontent.com/24813620/29902915-9333cef0-8dc6-11e7-9439-fdedd1a957d7.png)
