### ISSUE TITLE
Display Count of Volunteer Projects

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1183]
Click Volunteers
For the volunteers, above State, Country, please add text and icon to indicate how many projects user is matched for.

**<Project_Icon> x Projects**

- Sample materialize css icons

![image](https://user-images.githubusercontent.com/24813620/29857083-6735cbe6-8d1c-11e7-9bd6-8a570d04be5c.png)
![image](https://user-images.githubusercontent.com/24813620/29857086-6f6f82a2-8d1c-11e7-93c9-7f8f3aa97e25.png)
![image](https://user-images.githubusercontent.com/24813620/29857172-ece2f3c2-8d1c-11e7-8fa5-35986a22a39b.png)
![image](https://user-images.githubusercontent.com/24813620/29857192-088f8676-8d1d-11e7-96d9-a8beac92f05e.png)

![image](https://user-images.githubusercontent.com/24813620/29857018-fa8f8810-8d1b-11e7-9107-e9802fbcf33d.png)

![image](https://user-images.githubusercontent.com/24813620/29857007-ec8d786c-8d1b-11e7-8012-7a9b6d277062.png)

**Comment by felipealves-gnu** [comment]
Can you draw how would want it on that screen ?

**Comment by Code4SocialGood** [comment]
![image](https://user-images.githubusercontent.com/24813620/30089849-04ce1cac-9275-11e7-8362-cfb9f2c9a656.png)
