### ISSUE TITLE
Enter Skill Tag - enforce formatting

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1194]
**Web Pages**
1. Login as nonprofit user:  testnonprofituser2@gmail.com / Opensource5social!
Click Create Project
2. Login as nonprofit user:   testvolunteeruser2@gmail.com / Opensource5social!
Click My Settings

**Requirement**
When user enter skill, enforce the following formatting rule:
1. value should be small case: 
Please covert letters to all small case when use enter input to test field. If we can't achieve it, then when save to backend, covert to all small case
2. don't allow space, must be a single word. it can be dash connected word (like ruby-on-rail)

Add an information icon to the right of "Enter your own skills". When the icon is hovered, display tooltip: "Enter a skill with all small case, and one single word (could be multi words connected with dash)"

![image](https://user-images.githubusercontent.com/24813620/29944146-ebd85198-8e61-11e7-88fc-4f3cb081b3dc.png)

**Comment by trishulpani** [comment]
@Code4SocialGood - Please review the fix. Thanks.

**Comment by Code4SocialGood** [comment]
@trishulpani 
1. Thank you for the fix! The PR has been merged.
2. You have been invited to the repositories (c4sg-web and c4sg-services). After accept the invitation, you could place your username under the issues you are working on.

**Comment by trishulpani** [comment]
@Code4SocialGood 
Thanks for the invite. Is there a Slack channel for the group?

**Comment by Code4SocialGood** [comment]
@trishulpani Please go to Code for Social Good web site, from the footer, click Chat. That is how to join the Slack team. Let me know if you have trouble join.
