### ISSUE TITLE
Help Page

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1216]
Form where this page is launched: Footer (see issue #1215)
Page title: Help Page

Page content: Use Collapsible (http://materializecss.com/collapsible.html)
Note: not sure whether your need this plug-in to implement the collapsible in angular 2 environment: https://github.com/InfomediaLtd/angular2-materialize
https://infomedialtd.github.io/angular2-materialize/#/Collapsible

Add one collapsible item as below:

![image](https://user-images.githubusercontent.com/24813620/30168684-bee9f04e-93af-11e7-99ce-43786484cfb5.png)

**Comment by younjiwoo** [comment]
I'd like to work on this, but I need some more context. :)

**Comment by Code4SocialGood** [comment]
@younjiwoo Sorry I missed  your comment. 

From footer, you could click Help link. That suppose to open Help page, which is a new web page. This issue is to create that new page, which including the necessary rounting, html, scss, ts files.

**Comment by Code4SocialGood** [comment]
Add another collapsed item:

**Who can be post projects on Code for Social Good?**
- Nonprofit Organizations
- Open Source Projects
- Social Good Projects that is not for profit

**Comment by Code4SocialGood** [comment]
Add another collapsed item:

**Organization Users**
Register
Login
Complete User Profile
Complete Organization Profile
Create Project
Receive Applications 
Interview Applicants (with your preferred method)
Accept / Deny Applicant
Give Badges to Accepted Volunteers as Recognition
Browse volunteer profiles and reach out for potential candidates

**Comment by Code4SocialGood** [comment]
Add another collapsed item:

**Volunteer Users**
Register
Login
Complete User Profile
    You need to complete user profile before apply for projects
    You can choose whether to publish your profile on the web site
    You can choose whether to receive notification if new project is posted
Browse Projects 
Apply for Project
Interview (project owner will contact you)
Accepted / Denied
Receive Badges if recognition by project owner
Receive notifications for new projects

**Comment by Code4SocialGood** [comment]
Add another collapsed item:

**Chat - Launch from footer**
Join Code for Social Good chat room, join the active technical volunteer community. 
Collaborate with team members, post technical questions, or simply say Hi.
You are never alone!

**Comment by Code4SocialGood** [comment]
Resolved in PR #1470
