### ISSUE TITLE
Issue setting up frontend local environment - Webpack failed

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1225]
This issue is only seen by new joined developers when setting up their environment. Issue with leftlet and mapviewer. Please investigate:
1. What caused the issue
2. Do we need leftlet and mapviewer? Those modules should be imported before we switched to google map. If not needed, please remove the modules.

![image](https://user-images.githubusercontent.com/24813620/30241992-868b1eee-9553-11e7-89e4-6df1648b0274.png)

![image](https://user-images.githubusercontent.com/24813620/30241995-94537de6-9553-11e7-8608-9b643e8f567f.png)

![image](https://user-images.githubusercontent.com/24813620/30242002-b7946bf8-9553-11e7-8eef-19563fdc032d.png)

![image](https://user-images.githubusercontent.com/24813620/30242003-c50c2212-9553-11e7-89ed-dbe38856df97.png)

**Comment by bbmoz** [comment]
This might have something to do with a mismatch of the installed versions. I would recommend that someone with a working version of the project create a npm lockfile and then committing it. See https://docs.npmjs.com/cli/shrinkwrap. We could also set up something like an .nvmrc to version a common version of Node.

**Comment by russon77** [comment]
could the affected devs specify their npm and node versions?

`npm -v`
`node -v`

**Comment by Code4SocialGood** [comment]
@russon77 
OS: Windows 10

**Developer who has issue:** 
node -v: v6.11.3
npm -v: 3.10.10

**Jenny who has no issue:**
node -v: 6.10.0
npm -v: 3.10.10

**Comment by russon77** [comment]
i would recommend upgrading node and npm regardless. let's see. is everyone on the latest `master` branch, 100% sure?

what's the installed typescript versions?

**Comment by russon77** [comment]
affected developers, please pull the latest code from master and let me know if your issue persists. thanks!

**Comment by Code4SocialGood** [comment]
Issue Resolved, tested on node 6.11.3 and 8.2.1
