### ISSUE TITLE
Display description section for Project/Volunteer/Organization page

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1242]
Web Pages: Project List, Volunteer List, Organization List

Issue: For the description of project/volunteer/organization, we would like to display so that:
1. Max of 3 lines of text are displayed
2. At the end of line, follow by ... if the description can't be fully displayed
3. The last word the is displayed should be a full word, not being trimmed

- **Last word get trimmed**

![image](https://user-images.githubusercontent.com/24813620/30382725-8ab640ba-9865-11e7-83d1-f1d90e7f66ae.png)

- **More than 3 lines displayed**

![image](https://user-images.githubusercontent.com/24813620/30382784-adfee50e-9865-11e7-8b01-54de9de7044d.png)

- **Seems more words could be displayed**

![image](https://user-images.githubusercontent.com/24813620/30382808-c308d9fa-9865-11e7-82a1-fa7dbbeab89c.png)

**Comment by nmcolome** [comment]
Hi! I’m a first-time contributor and was hoping to help out with this issue. I'm working with @squeemishly and @rwilhel and we noticed nobody was assigned to it. Thanks!

**Comment by Code4SocialGood** [comment]
Resolved in PR#1283
