### ISSUE TITLE
Remove Slack Field

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1251]
Slack username field on the web site is causing lots of confusion. Please comment out the code so we don't show this field. Please comment out instead of deleting the code, in case we want to show the field in the future.

- Login as Volunteer User (testvolunteeruser2@gmail.com / Opensource5social!) or Organization User(testnonprofituser2@gmail.com / Opensource5social!)
- Click My Settings
- Comment out the code so that Slack Username text field is not displaying
- Click Volunteers
- Click an volunteer
- Comment out the code so that Slack icon is not displaying under user avatar.

**Comment by nmcolome** [comment]
Hi! I’m a first-time contributor and was hoping to help out with this issue. I'm working with @squeemishly and @rwilhel and we noticed nobody was assigned to it. Thanks!

**Comment by Code4SocialGood** [comment]
Resolved in PR #1282
