### ISSUE TITLE
Home Page - Map - Statistics - Color

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1273]
Change the statistics section for the map from orange to teal. 

![image](https://user-images.githubusercontent.com/24813620/30525957-3268d27c-9bd7-11e7-94f9-7e5d330e772d.png)

**Comment by nmcolome** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by Code4SocialGood** [comment]
@nmcolome Thank you for volunteer to work on this problem! 
1. This issue has not been picked up by volunteers, please feel free to put your github username under this issue before you start working on it.
2. The Setup instruction could be found on the wiki page: https://github.com/Code4SocialGood/c4sg-services/wiki/Development
3. If you have any questions, you could also chat with @jenny on Slack (you could join by clicking Chat link on the footer of the web site: code4socialgood.org

**Comment by Code4SocialGood** [comment]
Resolved in PR #1281
