### ISSUE TITLE
Remove Slack icon

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1288]
Login as Nonprofit User ( testnonprofituser2@gmail.com / Opensource5social!) 
Click Volunteers
Click an volunteer
Comment out the code so that Slack icon is not displaying under user avatar.

![image](https://user-images.githubusercontent.com/24813620/30629736-23ec72a8-9da3-11e7-91e2-729a60bcf753.png)

**Comment by Pewpal** [comment]
#1311 includes the HTML change for #1288
