### ISSUE TITLE
Footer - Rearrange items

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1289]
Please rearrange footer as below:
1. Add bold text of ABOUT and COMMUNITY
2. Rearrange items under ABOUT and COMMUNITY

![image](https://user-images.githubusercontent.com/24813620/30656786-d98cf8c4-9dfa-11e7-94e7-a74ead7f4484.png)

![image](https://user-images.githubusercontent.com/24813620/30656808-e3869434-9dfa-11e7-9771-de541325d7ad.png)

**Comment by Pewpal** [comment]
#1311 contains the change for #1289
