### ISSUE TITLE
Our Stories Page

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1290]
1. In footer, under Help link, add link: "Our Stories"

2. When this page is launched, display:
Page title: Our Stories (green background with white text, same as other pages)
Page content: Coming Soon!

**Comment by Code4SocialGood** [comment]
@Kiranpreet The PR #1316 has been merged. From where do I launch Our Stories page?

**Comment by Kiranpreet** [comment]
Its in the Footer under the Help link, as required in the issue.
![ourstorieslink](https://user-images.githubusercontent.com/13419653/30837642-f579c582-a22b-11e7-97fe-2847dbc76417.PNG)
