### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1299]
1. On footer, under Help, add "Contact Us"
2. When user clicks Contact Us, launch the Contact Us Page

Page Title: Contact Us
Page Content: 
	A standard Contact Us form:
		Your Name
		Your Email:
		Your Comments:
		Submit button

	You can also reach us at info@code4socialgood.org.

**Comment by Pewpal** [comment]
#1311 now contains my implementation of the Contact component

**Comment by Pewpal** [comment]
Hmm, not sure if closing an issue is bad practice, my intention was to keep things tidy and properly directly attention to the pull request with the solution for the issue. Please let me know, for now I'll hold off on closing more.

**Comment by Code4SocialGood** [comment]
@Pewpal Contact Us Page looks great, thanks!

Question: Can frontend (Angular 2) send out emails directly, or it has to call the backend to send out email through email service?
