### ISSUE TITLE
Project List Page - Pagination

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#13]
_From @Code4SocialGood on March 7, 2017 19:42_

- **Web Path**
Home Page -> Opportunities

- **Requirement**
Implement pagination in the page.
Refer to hos Volunteers List Page implements pagination.

_Copied from original issue: Code4SocialGood/C4SG#454_

**Comment by praveenaraoa** [comment]
PR for this issue is merged.
