### ISSUE TITLE
Home>Consultants Spelling error

### ISSUE THREAD

**Issue by Genexodus** [Code4SocialGood/c4sg-web#1333]
When Clicking the consultants link at the bottom of the page (Dev and Production) - 
The guiding text has a spelling error for "**Within**" It is spelled "**Withing**" This should be _corrected_. 

Considered revising text statement from:
_Have a question and want to talk to a subject area expert? Leave your request below and you will be contacted by a consultant withing 3 days_

To:
_Have a question, or would you like to talk to a subject area expert? Leave your request below and you will be contacted by a consultant within 3 days._

**Comment by Code4SocialGood** [comment]
@Genexodus Thank you for creating this issue that helps improve the web site. Please create more issues as you see enhancement opportunities!
