### ISSUE TITLE
Home> Partners> ContactUS link

### ISSUE THREAD

**Issue by bshores** [Code4SocialGood/c4sg-web#1334]
https://app.code4socialgood.org/partners

At the bottom of the page the "Contact Us" link doesn't seem to fit the standards being set forth by the application. 

Clicking on the contact us page tries to open a mail app. It should take the user to the "Contact Us" page located here:
https://app.code4socialgood.org/contact

**Comment by Code4SocialGood** [comment]
Resolved in PR #1336
