### ISSUE TITLE
Home Page - Statistics - Add Country

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1348]
Add a line: Country: xx
Country count is by select distinct from User table and Organization table.

![image](https://user-images.githubusercontent.com/24813620/31446784-fb8cf94e-ae65-11e7-8042-87387f8ca934.png)

**Comment by felipealves-gnu** [comment]
@Code4SocialGood Do you need the sum of different countries both tables ?

**Comment by Code4SocialGood** [comment]
Yes, sum from both organization and user table

**Comment by felipealves-gnu** [comment]
Related backend issue code4socialgood/c4sg-services#390
