### ISSUE TITLE
Image Display Issue

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1353]
Image display is not good.  See screen shots below.

- Project List Page
The image is cut, but it looks fine

- Project Detail Page 
This image is displayed full, but is stretched which look bad. 
**Please fix the image display on this page. Make it look the same as Project List Page** 

https://app.code4socialgood.org/project/list/projects

**Project List Page**
![image](https://user-images.githubusercontent.com/24813620/31453767-d36328d6-ae78-11e7-9a0d-90f36915a327.png)

**Project View Page**
![image](https://user-images.githubusercontent.com/24813620/31453794-e7c351ca-ae78-11e7-81b9-ed2d6e11d77c.png)

**Comment by istride** [comment]
This one also might be solved by PR #1732

**Comment by Code4SocialGood** [comment]
Resolved in PR #1732
