### ISSUE TITLE
Responsive Design - Home Page - Display menu on header

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1356]
![image](https://user-images.githubusercontent.com/24813620/31509488-4a346276-af47-11e7-9317-51a483c1ae69.png)

**Comment by bealearnscode** [comment]
Do you mean you want something like a hamburger menu where the circle is?

**Comment by Code4SocialGood** [comment]
@bealearnscode It doesn't matter how the menu looks like, as long as we can see the menu and click on it.

**Comment by Code4SocialGood** [comment]
Resolved in #1505
