### ISSUE TITLE
Responsive Design - Home Page - Statistic on google map is trimmed

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1358]
![image](https://user-images.githubusercontent.com/24813620/31509608-bccb3670-af47-11e7-8bf9-2cea936da9d6.png)

**Comment by susendeep** [comment]
I think those facts must be below the map for mobile devices so that no further adjustments needs to be done for font side.

**Comment by Code4SocialGood** [comment]
@susendeep Agree!

**Comment by Code4SocialGood** [comment]
Resolved in PR #1576
