### ISSUE TITLE
Responsive Design - Project Detail Page - Apply/Bookmark

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1361]
Clicking the APPLY or BOOKMARK button doesn't direct to login page.
Note that it works fine if you test in google chrome, but it doesn't actually work if you test on mobile phone.

![image](https://user-images.githubusercontent.com/24813620/31509951-d2cbb354-af48-11e7-8e4a-6e7a0203e8dc.png)

**Comment by susendeep** [comment]
apply and bookmark button alignment is fixed already
![apply](https://user-images.githubusercontent.com/32482637/31731606-3ac02152-b453-11e7-8f10-75e9b9b5f0a7.PNG)
