### ISSUE TITLE
Home Page - Featured Project - Activator Icon

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1363]
Are we able to make the activator Icon more obvious so that use knows they can click on it?
See a reference in the second screen shot, which is obviously clickable.

![image](https://user-images.githubusercontent.com/24813620/31511028-0939f81c-af4c-11e7-842b-168bb4ad3d26.png)

![image](https://user-images.githubusercontent.com/24813620/31511101-3fa7c83e-af4c-11e7-9df7-ef27c30f8bba.png)

**Comment by bealearnscode** [comment]
I would like to work on this, but I don't know how to add myself to the project.

**Comment by bealearnscode** [comment]
I've added a floating action button to the cards, but the positioning if off and there is no interactivity. I can try to work on the former, but not sure what I can do with the latter just yet. Should I just focus on getting the button on the page?

**Comment by Code4SocialGood** [comment]
Keep the current UI display after consulting UI designer.
