### ISSUE TITLE
Project Page - The grey line is extended beyond border

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1386]
![image](https://user-images.githubusercontent.com/24813620/31581534-1b044a40-b134-11e7-9af5-efec1091d028.png)

**Comment by tylerjhevia** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!
