### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by jasonlucas907** [Code4SocialGood/c4sg-web#1388]
I am currently running into an error on npm install after cloning this repo.

```bash
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/jasonlucas/turing/MOD4/c4sg-web/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
```

I am using:

* node version 6.9.4
* npm version 3.10.10
* OSX

**Comment by Code4SocialGood** [comment]
@jasonlucas907 It is the first time this error is reported. We'll reach out to other developers who recently setup the frontend to see what are their local environment config.

**Comment by Code4SocialGood** [comment]
@jasonlucas907 
Please refer to this issue for the versions that have been tested: https://github.com/Code4SocialGood/c4sg-web/issues/1225

I realized your node is 6.9.4. This app has been tested on node no lower than 6.10.0.

**Comment by jhonemillan** [comment]
I just configured frontend environment, and all its ok, it works!.
OS: Linux Ubuntu 17.10
NPM: 5.5.1
Node: 9.2.0
