### ISSUE TITLE
Clarity on setup guide

### ISSUE THREAD

**Issue by lcaroselli** [Code4SocialGood/c4sg-web#1393]
Hello, just a small point for your consideration in the setup guide:
- It would be nice if the setup guide specified whether installation of both the backend and frontend is needed to make changes to a repo. As a first time contributor, it was unclear what was specifically needed for installation to make changes to the frontend. Both sections are split out, but maybe a note could be made whether or not the backend data is needed to make client-facing changes.

**Comment by Code4SocialGood** [comment]
@lcaroselli Thank you for the suggestion! We are current working on some changes which will impact the setup. We hope the changes could be wrapped up in one or two days, and we will update the setup document based on your suggestion.

**Comment by Code4SocialGood** [comment]
Close this issue. Moved to issue #1413
