### ISSUE TITLE
Environment Setup Issue - Local Frontend, Dev Backend - No command

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1402]
Scenario: Running frontend locally, point to backend on dev server.

Command Tried: npm run start:dev:remote

Error: 
![image](https://user-images.githubusercontent.com/24813620/31730933-0fc34ef2-b3f9-11e7-8c68-97728946bae4.png)

**Comment by felipealves-gnu** [comment]
@russon77 Can you help with that ?

**Comment by Code4SocialGood** [comment]
Resolved with PR #1412. 
Developer will launch with command: `npm run start:dev:heroku`
