### ISSUE TITLE
Help Page - Wireframe

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1405]
The page will be launched from footer.

The purpose of Help page is provide the help information to the users of our web site.
The contents is more of FAQ format, such as: 
- how to use our web site as volunteer user
- how to use our web site as nonprofit user
- how to use our web site as open source user
- what web browsers we support
- how to contact us when you have questions or feedback

**Comment by Code4SocialGood** [comment]
A sample help page: https://help.uber.com/

**Comment by younjiwoo** [comment]
@Code4SocialGood Could you give me some content to put it on the page?

**Comment by Code4SocialGood** [comment]
Help page is implemented as Collapsible.
