### ISSUE TITLE
wiki - Setup Document

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1413]
[Setup.docx](https://github.com/Code4SocialGood/c4sg-web/files/1397060/Setup.docx)

**Comment by Code4SocialGood** [comment]
**TODO**

It would be nice if the setup guide specified whether installation of both the backend and frontend is needed to make changes to a repo. As a first time contributor, it was unclear what was specifically needed for installation to make changes to the frontend. Both sections are split out, but maybe a note could be made whether or not the backend data is needed to make client-facing changes.

**Comment by SunyataZero** [comment]
This document has now been moved here: https://github.com/Code4SocialGood/c4sg-web/blob/master/docs/setup.md
