### ISSUE TITLE
Our Stories - Implement Swipeable Tabs

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1435]
In Our Stories Page:
1. Implement Swipeable Tabs: http://materializecss.com/tabs.html. 
Please note that you might need plug in of angular2-materialize: https://github.com/InfomediaLtd/angular2-materialize. 
Demo: https://infomedialtd.github.io/angular2-materialize/#/Tabs

2. Implement 3 tabs with titles:
Blog
Volunteer Stories
Nonprofit Stories

3. In each of the tab, display follow content:
Place a nice picture (find any nice picture from the web)
Place text: Coming Soon!

**Comment by asevans48** [comment]
Test case ticket is active. please let me know how you choose to implement this. Thanks.

**Comment by Code4SocialGood** [comment]
Resolved in PR#1506
