### ISSUE TITLE
Sign Up/Register Button on home page - Is it the same green as other green?

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1439]
![image](https://user-images.githubusercontent.com/24813620/32010700-31b1073c-b978-11e7-8253-45ab1c40b803.png)

**Comment by sabrinadowla14** [comment]
Hi,

Yes, it is the same color. The arrow is the image so the color might me be
little different than the others.

Thanks,

Sabrina
