### ISSUE TITLE
Home Page - Replace Featured Image with Video

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1441]
Please find a free video to replace featured image on home page

**Comment by kathkato** [comment]
Here are some resources for free videos:

- <a href="https://videos.pexels.com/">Pexels Videos</a>
- <a href="https://coverr.co/">Coverr</a>
- <a href="https://www.videezy.com/">Videezy</a>
- <a href="https://pixabay.com/videos/">Pixabay Videos</a>

**Comment by Code4SocialGood** [comment]
@joshisayali 
Please use this video: https://www.youtube.com/watch?v=RgFLWhHRAsg
If we find better video later, we can always switch.

**Comment by joshisayali** [comment]
Okay

**Comment by Code4SocialGood** [comment]
Some more sites: 
https://videos.pexels.com/
envato elements: they have a lot of stock videos but you would need a subscription. There are also some free ones.

**Comment by Code4SocialGood** [comment]
Resolved in PR #1548
