### ISSUE TITLE
Project View Page - Date format

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1458]
Login as nonprofit user:  testnonprofituser2@gmail.com / Opensource5social!
Click My Projects
Click a project
Change the Date format to be: MM/DD/YYYY

![image](https://user-images.githubusercontent.com/24813620/32184087-257238b6-bd69-11e7-826c-9e0c72ea65e2.png)

**Comment by sexta13** [comment]
I'm facing this issue when I enter in a project:
**_There was an unexpected error (type=Internal Server Error, status=500).
could not execute query; nested exception is org.hibernate.exception.GenericJDBCException: could not execute query_**

As it can be seen by opening for example the link below:

- https://c4sg-dev.herokuapp.com/api/projects/902/applicants
