### ISSUE TITLE
Performance Analysis

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1478]
Please use this tool for performance analysis on prod site: http://yslow.org/
Provide analysis report and recommendation on how to enhance the performance
If there are other popular tools, feel free to compare the tools

**Comment by asevans48** [comment]
Any standards for speed here?

**Comment by Code4SocialGood** [comment]
General guideline is 5 second. 
Please add performance test to your plan.
We can postpone load test to a later phase, since we only have hundreds of users and it is increasing steady but not a a fast speed (average of about 100 new users per week).
