### ISSUE TITLE
Our Stories - Pull from database and display

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1481]
Our Stories page contains 3 types of stories:
- C4SG Blogs
- Volunteer Stories
- Organization Stories

Each story contains:
- Image (this is a link)
- Title
- Body
- Volunteer/Organization Name
- Volunteer/Organization link

Please implement backend that:
- Create one table host the 3 types of stories. Define a story type column to identity the type. 
- Create one Restful API to save individual story.
- Create one Restful API to retrieve all stories. (In first iteration, we return all stories. Later we might defined additional API to return sub-list of stories).

Note: 
- Frontend is developed in another task. Fronted will use some hard code dummy content. 
- After backend is completed, frontend will integrate with backend to post stories and retrieve stories.

**Comment by Code4SocialGood** [comment]
Wireframe is attached for reference.
[OurStories_1.pdf](https://github.com/Code4SocialGood/c4sg-web/files/1443003/OurStories_1.pdf)

**Comment by damienburke** [comment]
@Code4SocialGood - may I start work on this?

**Comment by Code4SocialGood** [comment]
@damienburke Yes please!

**Comment by Code4SocialGood** [comment]
@damienburke You are invited to the repositories. Could you please accept the invitation, then place your github username under this Github issue?

**Comment by damienburke** [comment]
@Code4SocialGood 
wrt to the 2 fields:
1. Volunteer/Organization Name
2. Volunteer/Organization link

Q. Is a Volunteer modelled as a User (entity / table)?

I'm thinking this could be implemented at the data level by simply having an fk to the user_organization table. Is that close to intended solution?

I see user_organization will always have a user and org ref though..

**Comment by Code4SocialGood** [comment]
@damienburke Yes, both volunteers and organization users are modeled as user table.

**Comment by damienburke** [comment]
ok, so need a small bit more of a steer. Based on above comment, it sounds like I should model story:user as 1:1?

**Comment by damienburke** [comment]
whereas what I was initially asking, was perhaps I need to have the rel:
    story:user_organization as 1:1

, which would mean a more accurate desc of the story resource / dto would be:

mage (this is a link)
Title
Body
Volunteer Name
Volunteer link
Organization Name
Organization link

Besides, Im code complete, so would be great to get this answered ASAP so I can submit PR for review. Thanks!

**Comment by damienburke** [comment]
@Code4SocialGood - is there a known list of story types? Was thinking might be nice to use an emum to represent them.
Also, please let me know how the "users" rel should be modelled, as per above.
Thanks

**Comment by Code4SocialGood** [comment]
@damienburke 
1. One user could post as many stories as he likes. Therefore the mapping should be 1 user to many stories.
2. There are 3 story types: Stories posted by Volunteer Users, Stories posted by Organization Users, and, Stories posted by C4SG Admin. If you take a look at the Our Stories page, you could clear see those 3 sections.

**Comment by damienburke** [comment]
This is my current DDL:

    -- Create Table `user_story`
    DROP TABLE IF EXISTS `story`;
    CREATE TABLE `story`(
      `id`                  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
      `user_id`             INT(11) NOT NULL,
      `type`                VARCHAR(20) NOT NULL,
      `title`               VARCHAR(100) NOT NULL,
      `image_url`           VARCHAR(100) DEFAULT NULL,
      `body`                VARCHAR(100) DEFAULT NULL,
      `created_time`        TIMESTAMP NOT NULL DEFAULT '2017-001-01 00:00:00'
    );

**Comment by damienburke** [comment]
okay, I have this coded as far as I can go. gonna create PR - and perhaps my open requirements questions around the user rel can be addressed there?

**Comment by damienburke** [comment]
Created - https://github.com/Code4SocialGood/c4sg-services/pull/411
Cant add @Code4SocialGood as reviewer..

**Comment by damienburke** [comment]
@Code4SocialGood - please review following data mapping:

1. Each STORY database record will be saved against a user#id
2. These StoryDTO fields will be populated by joining to the user table:
Volunteer/Organization Name :  user.first_name + user.last_name
Volunteer/Organization link     :  user.personal_url

**Comment by Code4SocialGood** [comment]
@damienburke Thanks for the PR, the PR has been merged and this issue is closed. 

Are you interested in backend only or full stack? If full stack, then are you interested in integrating this story service with the frontend Our Stories page?

**Comment by damienburke** [comment]
@Code4SocialGood 
Thats great news, glad to have helped. At this point I'm just interested in backend work.
