### ISSUE TITLE
[Visual] Move text or image on Heroes Page

### ISSUE THREAD

**Issue by asevans48** [Code4SocialGood/c4sg-web#1493]
[11/04/2017][12:40am] [Visual] Heroes Image Obscures Text

Description:

The text in the heroes page is obscured by the image of the human. This is a visual enhancement issue  of low importance. However, the text is sometimes obscured by the image of the person.

Steps to Recreate:

1.) Go to homepage (https://code4socialgood.slack.com/messages)
2.) Got to Heroes Page 

Expected Result:

Text is legible and clearly visible

Actual Result:

Text is obscured by the image of the individual at times.

![screenshot from 2017-11-04 00-44-51](https://user-images.githubusercontent.com/5893953/32403200-7ad954c2-c0f9-11e7-9923-66cf53e4f126.png)

**Comment by Code4SocialGood** [comment]
@asevans48 The fix has been applied in dev, and will be released to prod tomorrow. I will update this issue when the prod release is complete.

**Comment by jhonemillan** [comment]
This is really open?

**Comment by jhonemillan** [comment]
@asevans48 i think you have made the change right?

**Comment by asevans48** [comment]
This is a visual bug. It is caught in my QA sweep.  The role of QA is to find and track bugs and make sure they do not reoccur. The developer's role is to fix them. Visual bugs are of low importance.

**Comment by asevans48** [comment]
@jhonemillan No this is not fixed (see above). Also the homepage video obscures the homepage text, menu bar, and logo. That is a quality problem, a big one. If it is on the homepage, you may want to consider fixing it.

**Comment by Code4SocialGood** [comment]
@asevans48 
1. The hero page is fixed. see below. Please close this issue
2. Please create a separate issue for the home page video.

![image](https://user-images.githubusercontent.com/24813620/33351856-6f0c4336-d46b-11e7-9af4-0ae27b858949.png)

**Comment by asevans48** [comment]
Awesome, getting to the video. Really busy building demo graphics for tomorrow for a really decent opportunity.
