### ISSUE TITLE
Home Page - Slow Loading

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1507]
Home page take a long time to load. Please investigate and improve.

1. What Cause the slowness?
- The page used to have user avatar loaded and display on the map, which is over 20MB. We took the avatars out, but the page is still slow. 

- We used to try static map. Here is a PR related to the effort (https://github.com/Code4SocialGood/c4sg-web/pull/183). We didn't go with static map at that time since it doesn't look at nice as a dynamic map.

- If the slow performance is slow due to the map, please consider how to improve it. With more and more users, load time will get worse and worse. If static map is the way to go, then we have to.

Approaches:
- Replace with static map
- Enhance backend restful API to only retrieve necessary information

What is already done:
- Purchase more power on the Heroku server. Upgraded from hobby to standard 1X plan

**Comment by bshores** [comment]
Did some basic analysis with **Fidler and Wireshark** to discover if there were any persistent and/or keep alive calls to the any API's that could of been causing any kind of network latency. This proved effective and help rule out **there is no ambiguous** web traffic that is being passed through the application. 

Second. Performed a multitude of performance tests using Jmeter. From simple HTTP requests to specific page attribute, using assertions to validate html requests. 

The largest test consisted for **40 Users, 30 second ramp up, the load was held for 4 minutes**. While the load test was running, I navigated through the dev site. From a user perspective, **the load times were all less than 3 seconds**. Which signifies fast application load times. The map, took the longest to populate at 6 seconds, to populate the red markers. 

From an standards and quality perspective, I would say there are no major performance problems. This testing was not done prior the heroku upgrade. The upgrade could of helped with the latencies. 

**Final Analysis:**
There were a few outliers from the performance testing where the page would take between 3-5 seconds to load. Which signifies under extreme load, there could be latency problems. However, given in 4 minutes I pushed over 150,000 requests to and from the server.

Will plan to run a longer, more distributed test to find possible failure points. 

(With Jmeter the requests are made by virtual users, which are hitting application specific areas, that do not take into account times for navigation and typical human thoughts, and application interactions)

**Recommendation:**
On the map view, potential only highlight the countries that our volunteers are from, not plotting independent people. This would eventually have a maximum and would be easier to maintain as the site grows. 

Testing Details:
Google Chrome | 61.0.3163.100 (Official Build) (64-bit)
-- | --
Revision | 57c9d07b416b5a2ea23d28247300e4af36329bdc-refs/branch-heads/3163@{#1250}
OS | Mac OS X
JavaScript | V8 6.1.534.41
Flash | 27.0.0.183

**Comment by Code4SocialGood** [comment]
Please make the following change on the map:
1. For volunteers: 
- Remove the highlight for each volunteer user. 
- Highlight the country, and the volunteer count of that country.
- You might need to develop a restful service to return a list of countries, the country's geocode, and its user count.
- For user counts: count Active, Volunteer users in the country. 
```
select count(*) from user 
where role = 'V'
and status ='A'
and country = xxx
```

2. For organizations: no change
Let's leave it at this time. We can enhancement it in next iteration, after we finish refactor volunteers on map.

**Comment by Code4SocialGood** [comment]
First Iteration: Hard Code in Frontend
Second Iteration: Refactor backend with new restful API

**Please Implement this first iteration first.**

**Step 1: User Count: Done @jxwang16  **
select country, count(*) 
from user where status = 'A' and role = 'V' 
group by country
order by country

**Step 2: Geocode: Done @jxwang16 **
https://developers.google.com/maps/documentation/geocoding/intro

**Step 3: Hard code this list in frontend, and displays in home page map: TODO @karthijey **
Country, user count, Latitude, Longitude
ALB	1
ARE	1
ARG	2
AUS	2
BGR	1
BRA	8
CAN	9
CHE	2
CHL	1
COL	2
DEU	2
DZA	1
EGY	3
ESP	2
ETH	1
FIN	2
GBR	3
GHA	1
HUN	1
IDN	4
IND	14
IRL	1
IRN	1
ISR	1
ITA	3
JEY	1
KEN	2
LTU	1
MAR	2
MEX	3
MYS	3
NGA	1
NLD	3
NPL	2
PAK	4
PHL	4
POL	7
PRT	4
ROU	3
RUS	4
SDN	1
SRB	3
SVK	1
SWE	1
TUR	2
UKR	6
USA	309	37.0902400	95.7128910
VEN	1
ZAF	2
