### ISSUE TITLE
Our Stories - Change font

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1512]
In Volunteer Stories and Organization Stories:
- use the same font style and size as that of C$SG stories
- use the dark grey font color as it is now, no change

![image](https://user-images.githubusercontent.com/24813620/32416901-8d52e3f2-c216-11e7-8ea4-652bcabaec8a.png)

[OurStories_1.pdf](https://github.com/Code4SocialGood/c4sg-web/files/1444232/OurStories_1.pdf)

**Comment by vsarun150** [comment]
Hello,
Should the font style of 'Volunteer Story' march that of the ' Organization story' or is the the other way..?

**Comment by Code4SocialGood** [comment]
Implementation done. 

![image](https://user-images.githubusercontent.com/24813620/32538847-149bb894-c42d-11e7-80ba-7811b50e56b9.png)
