### ISSUE TITLE
Help - Text change for Chat

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1518]
Change from "Chat - Launch from footer" to "Chat"

Change the content to:
Join Code for Social Good chat room, join the active technical volunteer community. 
Collaborate with team members, post technical questions, or simply say Hi. 
Click Chat from the footer. (Note: make "Chat" underline, this is a hyperlink, click "Chat" will launch the Chat page)
**You are never alone!** (Note: make this line bold)

![image](https://user-images.githubusercontent.com/24813620/32417974-2dcfaf08-c227-11e7-9c20-b7f04c5515f5.png)

**Comment by chantal66** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by Code4SocialGood** [comment]
@chantal66 
1. Thank you for helping on this issue!
2. An invitation to join the repository has been sent to you. After you join, you could place your name under this issue.
3. An invitation to join the team Slack chat has been sent to you. That's where the team communicates. Feel free to join and say Hi

**Comment by Code4SocialGood** [comment]
Merged to #1530
