### ISSUE TITLE
Statistics on map is different from List Page

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1537]
![image](https://user-images.githubusercontent.com/24813620/32482031-904c0a34-c35b-11e7-9735-0f9d69cff312.png)

![image](https://user-images.githubusercontent.com/24813620/32482046-9fafbe44-c35b-11e7-8ae6-d2548d6380ff.png)

![image](https://user-images.githubusercontent.com/24813620/32482038-991168e4-c35b-11e7-8e0b-9de5e0b62bb8.png)

![image](https://user-images.githubusercontent.com/24813620/32482054-a528dce8-c35b-11e7-81d2-8194b490e0e0.png)

**Comment by karthijey** [comment]
@Code4SocialGood okay.

**Comment by Code4SocialGood** [comment]
Resolved in PR#1558
