### ISSUE TITLE
Heros Page - Same size for card

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1543]
Name: Only display first name, don't display last name
Location: Please display Country Name (no display state, no display country code)

![image](https://user-images.githubusercontent.com/24813620/32533233-222021de-c415-11e7-8ffe-6dbe9fd2da6e.png)

**Comment by loangelak** [comment]
Hi @Code4SocialGood, 

I am a newbie, I would like to take a stab at this.   I've made some changes locally here, shown below.  Please let me know if this is what you were thinking and if so I can make an PR request.   

<img width="419" alt="screen shot 2017-11-15 at 10 43 24 am" src="https://user-images.githubusercontent.com/22547780/32845081-e20db8ee-c9f1-11e7-91b6-95e2e5091e9f.png">

Thank you!

**Comment by Code4SocialGood** [comment]
@loangelak That looks great! Please submit a PR.

**Comment by Code4SocialGood** [comment]
@loangelak An email has sent to you inviting you to join the repository. After join, you could place your username on the Github issues you are working on.

The development team use Slack to communicate. If you are interested in joining, please join from here: http://join-our-slack.code4socialgood.org/

**Comment by Code4SocialGood** [comment]
Resolved in PR#1615
