### ISSUE TITLE
About Us Page - Refactor

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1568]
[C4SG About Page (1).docx](https://github.com/Code4SocialGood/c4sg-web/files/1460183/C4SG.About.Page.1.docx)

**Comment by Code4SocialGood** [comment]
@Lekshmisasidharan Please see attached the wireframe we just received. Please implement the About Us page base on this wireframe.

![image](https://user-images.githubusercontent.com/24813620/32761616-eb4519d6-c8b9-11e7-8e2b-68e28506e449.png)

**Comment by Lekshmisasidharan** [comment]
okay i will do that

**Comment by Code4SocialGood** [comment]
Resolved in PR#1619
