### ISSUE TITLE
Organization User - Enter your own skills - Iteration 2

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1578]
This is confusing for organization user. Need to rephrase.

**Iteration 1: Temporary solution, get it in fast**
AS-IS
```
Choose from popular skills below
Enter your own skills
```

TO-BE
```
Choose from popular skill list below
Enter new skills not available in the list 
```
**Iteration 2: Ask technical writer: what to use?**
Enter new skills not available in the list 
Enter additional skills
enter new skills

**Iteration 3: Long term solution**
Study how the situation is handled by other web sites. 
Refactor the skills section in our app.
See reference below from upwork.

![image](https://user-images.githubusercontent.com/24813620/32684667-934eecae-c64b-11e7-9604-4bbd83145728.png)

![image](https://user-images.githubusercontent.com/24813620/32685180-d0c7c906-c651-11e7-9377-9fbb01fec0e9.png)

![image](https://user-images.githubusercontent.com/24813620/32685181-d5259366-c651-11e7-9c99-b0a41fd01126.png)

![image](https://user-images.githubusercontent.com/24813620/32685182-d9047b8c-c651-11e7-8b64-ce11041a619a.png)

**Comment by andy5995** [comment]
I submitted PR #1577 as a suggestion. :)
