### ISSUE TITLE
C4SG - Documentation

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1607]
I notice a couple of things in the Local Environment Setup page (https://github.com/Code4SocialGood/c4sg-web/blob/master/docs/setup.md). First, it assumes Windows. I’ve adjusted, and will use a Windows box to make sure I have appropriate instructions while feeling my way through, but my primary dev environment is set up on my Mac, which is more friendly to the Linux world that seems to be more typically used by the open source community. It may make sense to describe setups for each environment. Perhaps more importantly though, I believe there may be an error on the setup page. In section 1.2, it lists the backend repository as being the same as the frontend (c4sg-web), but I believe the backend is different (c4sg-services).

**Comment by Code4SocialGood** [comment]
There is a spot where it lists both front and backend as being the same repo when they are not. You want the repo named c4sg-services

**Comment by Code4SocialGood** [comment]
Separate setup into 3 sections towards 3 developer roles:
1. Frontend Developer
2. Backend Developer
3. Full Stack Developer (it could refer to frontend setup and backend setup sections)

**Comment by professionalsql** [comment]
Per additional request from @Code4SocialGood, add a FAQ section to the bottom of the document.

**Comment by Code4SocialGood** [comment]
@professionalsql I didn't find the FAQ section, could you upload a screen shot here?

**Comment by Code4SocialGood** [comment]
Some input that could help newbies, please see if we could incorporate into our documentation.

_Here’s what works for me: I cloned the repos first and checked out the documentation. I expected some issues during the setup but having some experience with Spring Boot and Angular/Node helped - the build and deploy on my local machine went fine. Then I did a general code walk through - that is, I picked one element from the UI, inspected it using Chrome Dev tools and try to trace it till the very end i.e., pick an UI element such as a dynamic drop down or something and follow the code through Angular code asking yourself “where does this value come from” - trace the service, component, directive .... and then trace it back to Spring controller, services, data access .... once you do this a couple of times, you’ll get a fair idea of how the application is pieced  together. It’s like a jigsaw puzzle. You don’t have to know everything about everything. Trust me, this codebase is much easier to read than many I have seen before._

**Comment by Code4SocialGood** [comment]
To add:

Application Architecture
How to contribute to open source
References
