### ISSUE TITLE
About Us Page - Font

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1620]
Please check whether the text on green bar is bold. If not, make them bold.

![image](https://user-images.githubusercontent.com/24813620/32866457-91989d02-ca2d-11e7-9a4d-d89e87c8d9f1.png)

**Comment by loangelak** [comment]
@Code4SocialGood, 

Your about css file reflects that your your text on green bar (h2 tags) are currently bolded.

**Comment by Code4SocialGood** [comment]
Font is good, close this issue.
