### ISSUE TITLE
Home Page - Menu Item - Color

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1624]
On Mobile Device:
From Home Page, click menu
The menu items (PROJECTS, VOLUNTEERS, ORGANIZATIONS) are in white color, which is hard to see.
Can we change them to dark color?

**Comment by sync350** [comment]
Is this still open? It looks like https://github.com/Code4SocialGood/c4sg-web/pull/1773 was closed for code conflict?
