### ISSUE TITLE
Footer - Change Label: from Volunteer Heroes to Top Volunteers

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1633]
![image](https://user-images.githubusercontent.com/24813620/32898612-3a0575a2-caae-11e7-9959-df8651c3147d.png)

**Comment by loangelak** [comment]
@Code4SocialGood, 

My apologies, in fixing issue #1613 last night - I had attempted to fix issue #1633 (Change Label: from Volunteer Heroes to Top Volunteers).  

But it appears that my changes were correct and accepted but the file managed to merge into your appreciations folder versus the footer folder.

Let me know what I need to do to fix this.  My apologies for the inconvenience.

**Comment by Code4SocialGood** [comment]
@loangelak No worries at all!

Please:
1. Sync up stream to get the latest code in repository
2. Make the change (change from Volunteer Heroes to Top Volunteers in footer
3. Submit PR

Then we are done :)
