### ISSUE TITLE
About Us Page - Make the page content width 80%

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1646]
See comparison of the page below. 

![image](https://user-images.githubusercontent.com/24813620/32936877-9f43701c-cb3b-11e7-86e8-f80ed98ec045.png)

![image](https://user-images.githubusercontent.com/24813620/32936885-ab1cf70a-cb3b-11e7-9c24-c2ddd7fc3dbf.png)

**Comment by Lekshmisasidharan** [comment]
the issue is solved
