### ISSUE TITLE
Project Application: Add a line to applicant's profile on Code for Social Good

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1655]
Add a line like this: https://app.code4socialgood.org/user/view/11632

![image](https://user-images.githubusercontent.com/24813620/32993817-4db8609c-cd23-11e7-995d-414d2f76d280.png)

**Comment by felipealves-gnu** [comment]
@Code4SocialGood What do you mean by add a line ? Could you be more specific ?

**Comment by Code4SocialGood** [comment]
@felipealves-gnu Not sure about this issue, the description is unclear. Close this issue.
