### ISSUE TITLE
Top Volunteers Page - User the same Font Style as Consultants and Contact Us page

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1660]
![image](https://user-images.githubusercontent.com/24813620/33006447-04555a46-cd90-11e7-8329-9f7505dc5d2a.png)

![image](https://user-images.githubusercontent.com/24813620/33006460-0c4bb38a-cd90-11e7-935c-352324774095.png)

![image](https://user-images.githubusercontent.com/24813620/33006469-141503dc-cd90-11e7-8af2-7141554e7a10.png)

**Comment by uday060** [comment]
I am having around 7 years of industry experience on java related technologies and I want to contribute to this project. Please let me know how can I contribute to this

**Comment by Code4SocialGood** [comment]
@uday060 
1. You are invited to the c4sg-web and c4sg-services repository. Please accept the invitation, and then place your username under this issue.
2. Please follow up the setup document in the repository to setup your local dev environment.
3. The dev team communicate on Slack. Please join Slack team room (instruction on our github home page). 
4. Any questions, let us know here.

**Comment by Code4SocialGood** [comment]
Resolved in PR#1663.
