### ISSUE TITLE
When a project is closed - Send out email 

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1662]
Send out email to info@code4socialgood.org
Please reference the email sent when a user is deleted

**Comment by harshareddy75** [comment]
There are a few questions that I had regarding this - 
Who should the email be sent out to ? (I am assuming that the email has to be sent by info@code4socialgood.org instead of to) 
Additionally what should the email template be?

**Comment by Code4SocialGood** [comment]
1. Who should the email be sent out to ? 
From: info@code4socialgood.org
To: info@code4socialgood.org
The reason to send out this email is to notify C4SG admin to take down this closed project from other web sites that we marketing on

2. What should the email template be?
Please create a new email template.
Subject: A Project is closed
Body: A link to this project, like: https://app.code4socialgood.org/project/view/1142

**Comment by Code4SocialGood** [comment]
Resolved in PR: https://github.com/Code4SocialGood/c4sg-services/pull/402
