### ISSUE TITLE
Login on mobile device doesn't work

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1667]
@joshisayali 
Here is what user said:
```
android phones they are not working
also i have iphone 6s i tried again not working
```
Not sure how to test though if you don't have those type of phones

**Comment by brianandreasen1983** [comment]
Can we get a bit more detail on where this is failing. Using Facebook and Google+ authentication I am able to login from two different mobile devices iOS and Android is this only occurring with accounts signed up not using these methods?

**Comment by Code4SocialGood** [comment]
@brianandreasen1983 I tested this issue, couldn't recreate it. I am going to close it, unless we heard other users report this issue.
