### ISSUE TITLE
Video on homepage Fuzzy

### ISSUE THREAD

**Issue by afro-nolan** [Code4SocialGood/c4sg-web#1669]
The video clip on the homepage seems slightly fozzy and out of focus, It might just be becaus eof the size of my screen but it's definitley something to look into. You might need to adjust the resolution slightly to make sure it's responsive across all devices and screen sizes.

**Comment by Code4SocialGood** [comment]
@afro-nolan 

We got a new customized video, which is a much better quality. However, the new video is 68MB, while the current video is only 1MB. Are you aware of any best practice on the size limit of a video playing on home page?

If  you ping me (@jenny) in slack, I could show you the new video.
If you are not in slack yet and are interested in joining, please click the Chat link on the footer of our web site (code4socialgood.org)
