### ISSUE TITLE
Add to readme.md

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1671]
Some people joined our open source, but don't even know we have a production web site. 

Please add to readme.md for both c4sg-web and c4sg-services repositories
1. Prod web  site URL
2. The team communicate on Slack, join Slack team by this link: http://join-our-slack.code4socialgood.org/

**Comment by VitorDiass** [comment]
PR for #1672

**Comment by Code4SocialGood** [comment]
Resolved in PR #1672
