### ISSUE TITLE
Develop a new restful service to return counts, and, integrate with frontend.

### ISSUE THREAD

**Issue by mathif92** [Code4SocialGood/c4sg-web#1675]
It's needed to create a new restful service that returns counts in a single JSON object for the home page map's right panel.

This will enhance the performance.

**Comment by sumantsahney** [comment]
Hey,
Can I work on this one ?

**Comment by Code4SocialGood** [comment]
@sumantsahney , yes please. Thank you for your help!

**Comment by sumantsahney** [comment]
Cool. I will start working on it tomorrow.
Thanks,
Sumant
