### ISSUE TITLE
New Project Email Notification

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1679]
Change from text format to html format

[Check out this Taproot+ project.pdf](https://github.com/Code4SocialGood/c4sg-services/files/1153212/Check.out.this.Taproot.project.pdf)

[SocialCoder volunteering opportunities - July 2017 (HoloLens, Ethereum, Salesforce).pdf](https://github.com/Code4SocialGood/c4sg-services/files/1156395/SocialCoder.volunteering.opportunities.-.July.2017.HoloLens.Ethereum.Salesforce.pdf)

**Comment by sumantsahney** [comment]
Hey,
Can I work on this one ?

**Comment by linkin-park** [comment]
@Code4SocialGood what should be the template?
mainly the mid section of the html?
