### ISSUE TITLE
Add exception handling framework

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1681]

**Comment by damienburke** [comment]
@Code4SocialGood - something along these lines - https://www.toptal.com/java/spring-boot-rest-api-error-handling ?

**Comment by Code4SocialGood** [comment]
@damienburke 
Pleas consider exception handling framework on following exception types:
- System / Runtime exception
- Application exception (which can potentially define one exception per application error)
- Rest API exception (as shown in the toptal article)
- etc...

Could you check Spring framework to see what is the standard approach on handling exception in spring, then add exception handling to our application?

**Comment by damienburke** [comment]
@Code4SocialGood 
sounds good. Ill get started on some research first

**Comment by damienburke** [comment]
might get back to this later in month..
had a look at our code - and C4SGController does already provide some of what I believe is needed
