### ISSUE TITLE
Add Button for Slack

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1683]
Top Line: A PLATFORM BY VOLUNTEERS, FOR VOLUNTEERS

Left Side: Contribute to our open source project
Button: C4SG GITHUB PROJECT

Right Side: Join our volunteer community
Button: C4SG CHAT ROOM (this is the same link as Chat on the footer, http://join-our-slack.code4socialgood.org/)
Image icon on this button is the Slack image, 
![image](https://user-images.githubusercontent.com/24813620/33227015-e35df874-d15f-11e7-9775-2cb1807b72f2.png)

![image](https://user-images.githubusercontent.com/24813620/33226972-f6b72478-d15e-11e7-9ff6-cfa3d6aedfae.png)

**Comment by VitorDiass** [comment]
Where the github icon is load? I couldn't find any reference where the icon is settled. 
Thanks in advance

**Comment by jhonemillan** [comment]
Can you check the bottom of home page, there is a button with the text "GitHub Project"

**Comment by jhonemillan** [comment]
Home Component, line 378

**Comment by VitorDiass** [comment]
@jhonemillan i know where it is on the home page. my doubt is where is it located on the project? from where is it load? I wanted to know, to put the "Slack" icon with the same logic
