### ISSUE TITLE
Back Button Fix

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1694]
Please take out "<" from <BACK TO SEARCH

![image](https://user-images.githubusercontent.com/24813620/33279005-bae1d35c-d362-11e7-8038-f15241a46630.png)

**Comment by jhonemillan** [comment]
Is not the same that #1696

**Comment by Code4SocialGood** [comment]
Yes, it is fixed in PR #1696 now.
