### ISSUE TITLE
User View and Organization View Pages: BACK TO SEARCH button

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1695]
Changes have been done on Project View page:
- Remove the button from green title bar
- Add the button to the page content 

Please make the same changes on User View and Organization View pages.
- User View Page: Click Volunteers

![image](https://user-images.githubusercontent.com/24813620/33279312-c076e9a0-d363-11e7-837f-75291467aa08.png)

- Organization View Page: Click Organizations

![image](https://user-images.githubusercontent.com/24813620/33279331-d189de46-d363-11e7-9e78-225783bc8cf8.png)

**Comment by jhonemillan** [comment]
#1697 ??

**Comment by Code4SocialGood** [comment]
Resolved in PR #1697.
