### ISSUE TITLE
Project View Page - Image render

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1704]
Make the rendering of the two project images as circled the same as the one under Organization.

![image](https://user-images.githubusercontent.com/24813620/33358957-74e5d350-d491-11e7-92c8-0b66e80a9836.png)

**Comment by istride** [comment]
This might be solved by PR #1732

**Comment by Code4SocialGood** [comment]
Resolved in PR #1732
