### ISSUE TITLE
Featured Projects on Home Page - Display org logo if project has no image

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1705]
![image](https://user-images.githubusercontent.com/24813620/33359261-7b5f9f48-d493-11e7-907e-d9d324fe0c27.png)

**Comment by istride** [comment]
Good spot! I'll fix that now.

**Comment by Code4SocialGood** [comment]
Resolved in PR#1708

**Comment by Code4SocialGood** [comment]
Resolved in PR #1732
