### ISSUE TITLE
Skills tag: remove formatter

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1707]
Please reference 
- Issue: https://github.com/Code4SocialGood/c4sg-web/issues/1194
- PR: https://github.com/Code4SocialGood/c4sg-web/pull/1650/files

Please remove the enforcing format for skills tags in User Edit and Project Edit pages.
Please only make changes in the following two files, comment out the formatting code, don't delete them.
- user-edit.component.html
- project-edit.component.html

**Comment by lfkimura** [comment]
Hi everyone, May I work on this PR? it would be my first OS contribution.

**Comment by Code4SocialGood** [comment]
@lfkimura 

1. Welcome to join!
2. Yes, this issue is available, thank you for working on it!
3. You are invited to C4SG Github repositories. After receiving the invitation, you will be able to place your Github username under this issue.
4. The development team communicate in Slack. Feel free to join us from here: http://join-our-slack.code4socialgood.org/

**Comment by Code4SocialGood** [comment]
Resolved in PR #1769
