### ISSUE TITLE
Back to Search Button

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1713]
Pages: Project/User/Organization View Page
Change: 
1. Change the look to be an icon followed by label 
2. Change the label from "BACK TO SEARCH" to "BACK TO PROJECTS" or "BACK TO VOLUNTEERS" or "BACK TO ORGANIZATIONS"

![image](https://user-images.githubusercontent.com/24813620/33407902-0cd271bc-d539-11e7-82df-3a4f9307a262.png)

**Comment by Code4SocialGood** [comment]
@karthijey Could you please make it an icon followed by label. Please remove the button.

![image](https://user-images.githubusercontent.com/24813620/33637248-697e09b6-d9e5-11e7-9a6a-b751353f6ea7.png)

**Comment by karthijey** [comment]
@Code4SocialGood Please see PR #1749. Thanks.

**Comment by Code4SocialGood** [comment]
Resolved in PR#1749
