### ISSUE TITLE
Home Page- See More button

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1723]
Label is not fully displayed on iPhone6

![image](https://user-images.githubusercontent.com/24813620/33437118-948816b6-d5ac-11e7-9c88-a494e6dd4608.png)

**Comment by robbiegreiner** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by Code4SocialGood** [comment]
@robbiegreiner 
1. Thank for for the PR!
2. You are invited to the Github repositories. After join, you could place your username on any issues you'd like to work on.
3. The issue is not fixed by PR unfortunately. I tested on both Chrome (see screen shot below) and on an actual iPhone 6.

![image](https://user-images.githubusercontent.com/24813620/33636348-5e7e0aec-d9e1-11e7-93c1-8afe5347b287.png)

**Comment by Code4SocialGood** [comment]
Resolved
