### ISSUE TITLE
Home Page - Buttons overlapping

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1724]
Buttons are overlapping on iPhone6

![image](https://user-images.githubusercontent.com/24813620/33437201-c992b32a-d5ac-11e7-9da1-b70e014cbc59.png)

**Comment by hsanchez7934** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by Code4SocialGood** [comment]
@hsanchez7934 
Welcome to join the team!
Thank you for the PR!
You are invited to the Github repositories. After accept the invitation, you will be able to place your github username on the issues you are working on.

**Comment by Code4SocialGood** [comment]
Resolve in PR #1753
