### ISSUE TITLE
Display one line of text only

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1728]
Are we able to display one line of text only, don't let it wrap. 
If one line is not enough, trim the text. 
Trim based on the length of the text to fit in the space, instead of based on the number of characters, since length could be vary if based on number of characters.

![image](https://user-images.githubusercontent.com/24813620/33462666-65b1c8d0-d5fe-11e7-818d-8e3bd2ba84a5.png)

**Comment by robbiegreiner** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!
