### ISSUE TITLE
Home Page Video Rendering Enhancement

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1730]
1. Add wemp file: telling the browser play the video is wemp if mp4 does not work

2. Poster Image
From W3Schools - poster image - Specifies an image to be shown while the video is downloading, or until the user hits the play button. 
If you see CatchFire website.. they have poster image when screen size is reduced

**Comment by sync350** [comment]
I wouldn't mind taking a crack at this one.
