### ISSUE TITLE
Project/Volunteer/Organization List Page: Display Category

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1733]
**Pages** 
- Project List
- Volunteer List
- Organization List

**Note**
Category is an optional field for Project/Volunteer/Organization. 
There will be zero or one category for each Project/Volunteer/Organization. 

**Wireframe**

![image](https://user-images.githubusercontent.com/24813620/33510961-c9b69e84-d6d8-11e7-8480-44f71c9b23cd.png)

**Icons for Project/Volunteer Category**
![image](https://user-images.githubusercontent.com/24813620/33510983-1cac0020-d6d9-11e7-8519-802fd4d8490c.png)
![image](https://user-images.githubusercontent.com/24813620/33510984-20bf77be-d6d9-11e7-8ece-f3ec4c2c5501.png)
![image](https://user-images.githubusercontent.com/24813620/33510986-26a8e778-d6d9-11e7-9803-d9201634fa52.png)
![image](https://user-images.githubusercontent.com/24813620/33510988-2c75ad76-d6d9-11e7-8f80-9b748ecfb671.png)
![image](https://user-images.githubusercontent.com/24813620/33510989-31683c90-d6d9-11e7-90a5-d3757a2dac0f.png)
![image](https://user-images.githubusercontent.com/24813620/33510991-36bbeb9c-d6d9-11e7-8612-cdabbffd55ae.png)
![image](https://user-images.githubusercontent.com/24813620/33510993-3ad698c6-d6d9-11e7-88ac-712159bd32a0.png)
![image](https://user-images.githubusercontent.com/24813620/33510994-3f10e2e8-d6d9-11e7-9e5d-d1dc0b41b81d.png)
![image](https://user-images.githubusercontent.com/24813620/33510997-432992f8-d6d9-11e7-9ef6-d10c5b0a1b35.png)
![image](https://user-images.githubusercontent.com/24813620/33511000-488f4332-d6d9-11e7-89c2-f732b8a2dde0.png)

**Icons for Organization Category**
Please find some icons from the web

**Comment by rpirritano** [comment]
If this guy is still available, I would love to take it!

**Comment by Code4SocialGood** [comment]
@rpirritano This issue is available. Thank you for working on it!

**Comment by hibaAkroush** [comment]
is this issue still available?

**Comment by rpirritano** [comment]
@hibaAkroush you can take it, I will be unable to work on it at time...Thanks!

**Comment by hibaAkroush** [comment]
@rpirritano  thanks good luck with your other projects
