### ISSUE TITLE
Home Page - Section of Animated Text

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1747]
Please change the animation text in home page

1. Change to the text as below
JOIN US AND
CODE FOR [selector]! 
/offset/
Get started now! 

2. selectors are: Social Good, Fun, Experience, Interest, A Better World

3. User a smaller font fr the line: "Get started now!"

4. See wireframe below

![image](https://user-images.githubusercontent.com/24813620/33674475-506cb4d2-da75-11e7-9f36-14e6afb31612.png)

**Comment by dmgardiner25** [comment]
Are you looking for something like this with the "!" static? 
[![https://gyazo.com/dd8518ebc855b5577f4fbfe2887b6d99](https://i.gyazo.com/dd8518ebc855b5577f4fbfe2887b6d99.gif)](https://gyazo.com/dd8518ebc855b5577f4fbfe2887b6d99)
Or like this with it getting added on?
[![https://gyazo.com/1174ffe924e5cc8c640cd73ac365caf6](https://i.gyazo.com/1174ffe924e5cc8c640cd73ac365caf6.gif)](https://gyazo.com/1174ffe924e5cc8c640cd73ac365caf6)

**Comment by Code4SocialGood** [comment]
@dmgardiner25 

Thank you for joining!
You are invited to the github repositories. After accepting the invitation, you will be able to place your github username on the issues you are working on.

Regarding this Github issue:
1.  Please use "!" as added on (the second on your list)
2. Please change the first line from "IT DOESN"T MATTER IF YOU" to "JOIN US AND"
3. The animation for "INTEREST" and "A BETRER WORLD" works as expected, but not for "Social Good", "Fun", "Experience"

**Comment by Code4SocialGood** [comment]
Resolved in PR #1758
