### ISSUE TITLE
Our Stories - Post Stories

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1750]
Please work on this issue after finish issue #1509.

**Submit Story**
Click Share Your Stories
This button is only enabled when user logs in. Otherwise, display a tooltip. Please refer to how APPLY button works. 
This will lauch a new page, which display:
- Upload Picture (similar as other edit page)
- Story (a text area)
- Submit button
- Cancel button

**Save Story**
Upon submit, save to database. 
Please create new restful service to save and retrieve stories. 
Please create a new table to store the stories. 
The table should contain:
- ID
- User ID: nullable
- Org ID: nullable
- Image URL: nullable
- Story: nullable
- Type: not null 
	Values: V (Volunteer), O (Organization), C (C4SG) 
	This field distinguishes whether it is volunteer story or organization story or C4SG story
	When user click Submit from user interface, please check whether user is volunteer user or organization user. 
	1) For Volunteer user, populate User ID column, and Type = V 
	2) For Organization User, populate both User ID and Org ID column, and Type = O
	3) If Organization User and Org is C4SG, populate both User ID and Org ID column, and Type = C
	
- Create Timestamp
- etc

**Retrieve Story**
When launch Our Story page, retrieve:
- Latest C4SG story
- Latest 3 Volunteer Stories
- Latest 3 Organization Story

**Comment by Code4SocialGood** [comment]
Wireframe as below.

![image](https://user-images.githubusercontent.com/24813620/33971196-de4764e2-e03c-11e7-8638-958a8f0d6f7a.png)

**Comment by Code4SocialGood** [comment]
The StoryController has been created at backend. Pleas sync the stream to get the latest code.

**Comment by Code4SocialGood** [comment]
@lfkimura Could you work on Our Stories page when you have time?

**Comment by lfkimura** [comment]
OK, I will work on it as soon as possible.
