### ISSUE TITLE
Chat on Home Page

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1759]
The chat button on home page is wrong. See see below the comparison

**DEV**
![image](https://user-images.githubusercontent.com/24813620/33782779-9df717aa-dc1f-11e7-9564-ea764b8975b6.png)

**PROD**
![image](https://user-images.githubusercontent.com/24813620/33782788-a3f40f1e-dc1f-11e7-8be6-2b682bc53091.png)

**Comment by Code4SocialGood** [comment]
We use JavsScript for Tawk online chat plug in.

The integration is in index.html. There is no change to that file in recent months

![image](https://user-images.githubusercontent.com/24813620/33783377-215a6e6a-dc22-11e7-8d32-aa0d018cb19a.png)

Please research on the cause for this issue. 
Is this issue possibly related to JavaScript compression?
Our last prod release is PR #1720. This issue should have been introduced by PR after #1720.

![image](https://user-images.githubusercontent.com/24813620/33783470-9376749e-dc22-11e7-8b17-33a6e2292e1e.png)

**Comment by istride** [comment]
I've just noticed that the difference in appearance depends on the screen size of your device at the time the tawk.to is initialised.

**Comment by Code4SocialGood** [comment]
@istride  

What a good catch!!!

As you said, the different in appearance depends on the screen size/. I must have been testing responsive in Chrome and set to iPhone 6, and the chat appearance was not auto switched after I changed to desktop display. 

This is not an issue then, I am closing it.
