### ISSUE TITLE
Change the look and feel - Help Page

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1762]
See wireframe below.

[Help_1.pdf](https://github.com/Code4SocialGood/c4sg-web/files/1550460/Help_1.pdf)

**Comment by veredrec** [comment]
Hi! If this issue is still available, I can try and make the changes according to the new design.

**Comment by Code4SocialGood** [comment]
@veredrec 
Sorry that this issue has been resolved by another volunteer. You have been invited to Github repository. After accepting the invitation, you could please your username on any unassigned github issues that you are interested in working on.

You are also invited to the Slack, where the dev members communicate. Please feel free to join.

**Comment by veredrec** [comment]
@Code4SocialGood thanks for the update! 
I joined the Slack channel and I'll assign myself to issues in the future! :smile:

**Comment by Code4SocialGood** [comment]
Resolved in PR #1783
