### ISSUE TITLE
Google Analytics - Replace Track ID in index.html

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1764]
![image](https://user-images.githubusercontent.com/24813620/33961523-040c14b2-e014-11e7-8595-17193e20c078.png)

**Comment by VitorDiass** [comment]
Is this still open to resolve? If yes, i will work on it

**Comment by Code4SocialGood** [comment]
Resolved in PR #1772

@VitorDiass Thank you for the PR! You are invited to the github repositories. After join, you could place your username on the Github issues you are working on.
