### ISSUE TITLE
Evaluate Code for Social Good Security

### ISSUE THREAD

**Issue by Outte** [Code4SocialGood/c4sg-web#1765]
Using the network tab in the developer tools on Google Chrome, I was able to view sensitive information about every registered User, Organization, and Project on the site. This appears to be a very large vulnerability and must be addressed immediately.

**Comment by lfkimura** [comment]
Yes,  This vulnerability is a design issue. Those rest calls are used to calculate the statistcs number in the Home component but even though you change the evaluation logic to backend still there will be an open api (https://c4sg-prod.herokuapp.com//api/users) with those informations and the volunteers list with the same information.

**Comment by lfkimura** [comment]
@Code4SocialGood Would you have a solution for this issue?

**Comment by Code4SocialGood** [comment]
@lfkimura C4SG use JWT Token, which protect POST/PUT/DELETE but not GET. Is JWT Token able to protect GET method on backend rest call?

**Comment by lfkimura** [comment]
Yes @Code4SocialGood , JWT Token is able to protect GET method as well, it just has to use the Authorization Header like described in https://auth0.com/learn/json-web-tokens/. But I think the main question is How should we protect the user info besdes showing volunteers, organizations on its list page.

**Comment by lfkimura** [comment]
I mean https://app.code4socialgood.org/organization/list/organizations and https://app.code4socialgood.org/user/list pages should be able to be viewed unprotected, right?

**Comment by Code4SocialGood** [comment]
@lfkimura 
1. Organizations and Users are shown to public, without contact information. 
2. The contact information, such as email or phone, is only displayed for logged in user. 
3. The way we protect user information, is similar as LinkedIn. The difference is that in LinkedIn you have to be premium user to see users' contact, but in our app you have to be logged in.
4. We may enhance the application to place more protection on user information, such as only organization users can see contact, etc. Will add it to backlog.
