### ISSUE TITLE
Closed Project - Disable Apply Button

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1770]
When a project is closed, the Apply button should be disabled.
Note that a closed project won't show up in the Projects list. However, if the user has the link to the project, they can still access it.

![image](https://user-images.githubusercontent.com/24813620/34313847-104e5f2e-e734-11e7-80c9-5d6a9ddbf853.png)

**Comment by fernandomism** [comment]
Would it be possible to be given a URL of a closed project to test?

**Comment by HsuanTang** [comment]
Hi! I’m a first-time contributor and was hoping to help out with this issue.
