### ISSUE TITLE
Upgrade from Angular 2 to Angular 4

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1788]

**Comment by amyhartz** [comment]
Hi! I'm a first time contributor and would love to help out with this. Are you looking to upgrade to Angular 4 specifically or just the latest stable Angular version? I believe 5.1.3 is now the most recent version. Thanks!

**Comment by Code4SocialGood** [comment]
@amyhartz 
1. We would like to upgraded to the latest stable version. Haven't checked it for a while and last time we heard was version 4. It is evolving too fast :)
2. You have been invited to the repository. After accept, you could place your username on any unassigned Github issue.
3. The development team use Slack to communicate. You could join the chat by click the link on our web site home page. Feel free to join if interested.

**Comment by Code4SocialGood** [comment]
Resolved in PR#1795
