### ISSUE TITLE
Upgrade HttpClient

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1797]
Please refer to the comment in the PR that upgrade to Angular 4: https://github.com/Code4SocialGood/c4sg-web/pull/1795

_Upgrading to Angular version 4. This update requires separately importing the angular animations library. Due a bug in angular cli (angular/angular-cli#8930), upgrading to version 5 causes the build to fail._

_I didn't include it in this pull request but it would be nice to **upgrade to the new HttpClient also as Http is now deprecated. It would probably make sense to tackle this as a separate issue**._

**Comment by zhufeilong** [comment]
Get it. I had seen it before. But I thought it was not cause by my code. I
will investigate it, and fix it if I can.

**Comment by zhufeilong** [comment]
Hi, I have confirmed the error is caused by back-end. And when I run it
with my local back-end it works well.
