### ISSUE TITLE
Green bar alignment 

### ISSUE THREAD

**Issue by felipealves-gnu** [Code4SocialGood/c4sg-web#1799]
There is a big space between the video and the green bar.
<img width="1175" alt="screen shot 2018-01-30 at 08 52 04" src="https://user-images.githubusercontent.com/798927/35565147-1a7ec7f6-059b-11e8-9372-68ba8d1b9290.png">

**Comment by Code4SocialGood** [comment]
@felipealves-gnu Which environment? I checked both DEV and PROD, couldn't see the big space.

**Comment by Code4SocialGood** [comment]
![image](https://user-images.githubusercontent.com/24813620/35631335-3eabbb06-0669-11e8-97a6-229218546d29.png)

**Comment by felipealves-gnu** [comment]
@Code4SocialGood Didi you try expand your browser beyond the screen ?

**Comment by Code4SocialGood** [comment]
This is a responsive issue. If set the browser as iPad Pro, you will see the issue.

**Comment by felipealves-gnu** [comment]
Ok

**Comment by ameseee** [comment]
@Code4SocialGood I'd be happy to take this issue if @felipealves-gnu isn't working on it already?
