### ISSUE TITLE
Username overlaps with skills

### ISSUE THREAD

**Issue by emilycoleman** [Code4SocialGood/c4sg-web#1812]
In the Volunteer view page, a sufficiently long username overlaps with that person's list of skills.

<img width="558" alt="screen shot 2018-02-20 at 3 05 09 pm" src="https://user-images.githubusercontent.com/14080780/36446613-d9e2dac8-164f-11e8-8288-d1187410390b.png">

**Comment by adaynit** [comment]
I would like to help fix it. Where can I access the code?

**Comment by emilycoleman** [comment]
@adaynit You can find the setup instructions [here](https://github.com/Code4SocialGood/c4sg-web/blob/master/docs/setup.md), and more general development information is [here](https://github.com/Code4SocialGood/c4sg-services/wiki).

**Comment by adaynit** [comment]
Perhaps my question wasn't specific enough. If I want to fix the volunteer view page, what is the file name and which folder can it be found it?

**Comment by emilycoleman** [comment]
@adaynit In app/user/view/user-view.component.html
