### ISSUE TITLE
Tell the user that there is a max of 10 skills for the profile

### ISSUE THREAD

**Issue by SunyataZero** [Code4SocialGood/c4sg-web#1813]
Under "My Settings" -> "My Skills" it's possible to add up to 10 skills but not more. I would like this limit to be more clear than now, as right now when i try to add an 11th skill nothing happens, which might confuse the user. Maybe we can add some "inline" documentation which tells the user that she has reached the max number of skills, or find some other way of dealing with this?

![image](https://user-images.githubusercontent.com/10245688/36608287-b1aaa60e-18c9-11e8-8c7b-e360b5919f25.png)

**Comment by farrahD** [comment]
Can I try out this issue?
