### ISSUE TITLE
Numbers dissapeared 

### ISSUE THREAD

**Issue by felipealves-gnu** [Code4SocialGood/c4sg-web#1817]
All the numbers dissapeared !!!

![selection_058](https://user-images.githubusercontent.com/798927/37096507-3286ddaa-21ef-11e8-9ac2-657ba7f90632.png)

**Comment by zhufeilong** [comment]
It looks good on my local-dev environment. And I have gone to https://app.code4socialgood.org/ , and it's OK too.
So could you give some more details?

**Comment by felipealves-gnu** [comment]
Yeah, it's working.... it's just an annoying proxy server in my company is blocking those numbers. I will close #1817
