### ISSUE TITLE
Keyword Search Title Alignment Issues on Projects, Volunteers, and Organizations Page

### ISSUE THREAD

**Issue by gabriellecozart** [Code4SocialGood/c4sg-web#1819]
<img width="1147" alt="screen shot 2018-03-15 at 2 39 53 pm" src="https://user-images.githubusercontent.com/9090353/37484487-07582cb2-285f-11e8-9466-825e868b7bba.png">

**Comment by zhufeilong** [comment]
I use Chrome, And the page looks right. 
This should be a compatibility issue. Could you write down the browser you used.

**Comment by gabriellecozart** [comment]
I'm not sure which browser I was using at the time (I think Opera), but the issue is with all browsers when the width of the window shrinks. Try adjusting the screen size. I guess I should have realized it was a responsive issue. 

![image](https://user-images.githubusercontent.com/9090353/37856820-ef8f1a4a-2ecc-11e8-9e9f-c644de410cc2.png)

![image](https://user-images.githubusercontent.com/9090353/37856837-124b9bda-2ecd-11e8-9ac3-3f2e41c981a1.png)

**Comment by affilnost** [comment]
I was able to reproduce this issue, I just made the browser's window smaller, see the screenshot.
I use Chrome 65.0.3325.162.
<img width="1203" alt="1819_screen" src="https://user-images.githubusercontent.com/2981884/37876041-8bfcbc22-3047-11e8-81cc-8e14735614c2.png">
