### ISSUE TITLE
Test Server: Setup developer's use account to access test database

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#191]
1. Create a user account, c4sgdev, on test database
2. Grant CRUD access: 
`GRANT SELECT,INSERT,UPDATE,DELETE ON heroku_4843aa39a46a434.* TO 'c4sgdev';`

**Comment by Code4SocialGood** [comment]
Not an option with free plan. Will consider alternate approach of Amazon web service.

**Comment by wjhurley** [comment]
Looked into ClearDB's plans and only options that allow creating new users are single-tenant plans, which start at $75/month.
