### ISSUE TITLE
Test Server - Try out Amazon Beanstalk

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#193]
- **Initiative**
Heroku's ClearDB free plan has restrictions on single user account, etc.

- **Try Out**
Amazon Beanstalk: https://aws.amazon.com/elasticbeanstalk/
Spring Deployment: http://docs.spring.io/spring-boot/docs/current/reference/html/cloud-deployment.html

- **Note**
Please ask @russon77 whether we have Amazon account (from Discourse forum hosting)

**Comment by russon77** [comment]
Yes, there is an existing amazon account - it's currently using the free ec2 VPS for hosting discourse.

**Comment by Code4SocialGood** [comment]
One at a time. Heroku for first release.
