### ISSUE TITLE
User List Page - Display

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#205]
- **Web Path** 
Home Page -> Volunteers

- **Requirement**
1. Retrieve and display Volunteer's state and country:
If both state and country are set by the user, display state, country
If either state or country are set by the user, display either state or country
If none of state or country are set, display 'Virtual'

2. Retrieves and display Volunteer title.
Currently the title field is not available in JSON object. Please use a hard code value for now.

2. Retrieves and display Volunteer Skill tags. 
There will be a max of 6 skill tags, display in 2x3 layout.

3. Retrieves and display Joined Date.
Joined data is the createdTime in JSON object.

- **Wireframe**
![image](https://cloud.githubusercontent.com/assets/24813620/24783022/6451b7e8-1b0f-11e7-8cc7-43dfdef83960.png)

- **Current Page**
We shouldn't display "null"
![image](https://cloud.githubusercontent.com/assets/24813620/24783037/81a58cf2-1b0f-11e7-92e1-68ee1812b42b.png)

**Comment by hdwilber** [comment]
Hi, mates.
Here, I have some advances for this. I need the feedback as much as possible. 
I am able to code pixel perfect pages, but I am not artist. :D
Help!

![code for social good - google chrome_004](https://cloud.githubusercontent.com/assets/16395551/24835865/f4504d8e-1cfc-11e7-9fbc-a681fd0b993a.png)

Thanks in advance

**Comment by Code4SocialGood** [comment]
Could you submit a PR with the code, so that people can provide feedback?
