### ISSUE TITLE
Home Page - Auth - Create Organization when Nonprofit User Sign Up / Login

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#218]
- **Requirement**
When a nonprofit user is signed up (or login), along with creating the user in the database, also:
1. Create an organization in the organization table. Organization Name is the only required field when creating an organizaiton. Pleas supply with a template org name such as "My Organization".
2. Insert a row in the user_organization table

- **Test**
1. Currently, if a nonprofit user signs up and logs in, his drop down menu doesn't contain My Organization, because he has no organization.
2. After this task, if a nonprofit user signs up and logs in, his drop down menu contains My Organization.

**Comment by jekcosty** [comment]
The suggested approach IMHO breaks the Single Responsibility design principle. 
As an alternate approach, If I am not mistaken, there was suppose to be a screen for Create an Organization and if so have that as a dropdown for the non-profit user when no organization entity exists and once created then have the My Organization as a replacement.

**Comment by Code4SocialGood** [comment]
I am implementing as you suggested.
