### ISSUE TITLE
Organization List Page - Modal for Delete Button

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#22]
_From @Code4SocialGood on March 7, 2017 3:33_

- **Web Path**
Home Page -> Nonprofits

- **Requirement**
1. When Delete button is clicked,  a modal is popup. Currently the modal only have Yes option. Please add No option.
2. The text should be Confirm **_Nonprofit_** Delete

- **Screen Shot**

![image](https://cloud.githubusercontent.com/assets/24813620/23640588/5869b8fe-02b4-11e7-8aeb-c072893a348f.png)

_Copied from original issue: Code4SocialGood/C4SG#445_

**Comment by suneelakodali** [comment]
Added "No" button to the Delete Modal popup.  Changed the popup text to 'Confirm Nonprofile Delete'"
