### ISSUE TITLE
Data Types constructors and instantiating

### ISSUE THREAD

**Issue by hdwilber** [Code4SocialGood/c4sg-web#230]
When I had to add more attributes to a User class. The compiler asks me to check the parameters for constructor of the class that is being instantiated.
That forces us to change all codes where is being instantiated.
I propose to use.
```
export class User {
  id: number;
  name: string;
  email: string;
  ... // And so on.
}
```
Let's keep the default constructor.

**Comment by russon77** [comment]
do we ever actually call `new T()`? i was under the impression that we mostly used the types as models that reflected the return values of the backend.

we should at least include `public`/`private` if we move out of the constructor.

**Comment by hdwilber** [comment]
Well, when creating a new instance like this...
[https://github.com/Code4SocialGood/c4sg-web/blob/master/src/app/user/profile/user-profile.component.ts#L51](url)

Adding scope to its attributes could be nice, too.
