### ISSUE TITLE
Performance on Initial Invocation of the Application

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#234]
First time user invokes the application, Opportunities, Volunteers, and Organizations pages have long response time. Subsequent calls are not an issue since they are now cached.

Research if there is anything we could do to improve the response time. At least, let's add preloader.

**Comment by russon77** [comment]
agree with the preloader 👍 also, let's get pagination support across the board, so that the response time can be significantly reduced.
