### ISSUE TITLE
Image display on list page

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#268]
- **Web Path**
Opportunities
Volunteers
Nonprofits

- **Requirement**
If there is no image, don't display anything.

- **Current Page**
![image](https://cloud.githubusercontent.com/assets/24813620/25566906/a62cbc52-2da8-11e7-885a-9e334ae1b9f9.png)

**Comment by hdwilber** [comment]
If do not show anything, then there will be an empty space.
Really, do you want that ?

**Comment by Code4SocialGood** [comment]
Our choices: 1. empty space 2. a default image

For avatar, a default image could work. But for project image or organization logo, default image doesn't work well. Therefore, let's give an empty space for now.

Please note that when a user/org/project is created, we might assign a default image until user upload a different one. So it is likely the image is never empty.  We haven't finalize it yet due to the transition in progress to S3.

If empty space is not your favorite, do you have a better idea?

**Comment by Code4SocialGood** [comment]
Resolved with PR
