### ISSUE TITLE
Project View Page - Delete Buttons

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#276]
- **Web Path**
Login as nonprofit user: testnonprofituser2@gmail.com / Opensource5social!
Click on Opportunities
Click on an opportunity name

- **Requirement**
Delete button: Popup Are you Sure. Upon Yes, call Rest API to delete the project
To verify the project is deleted, go to Opportunities, and verify the project is not showing up.

**Comment by Code4SocialGood** [comment]
It is more convenient to test with admin user. 

**Web Path**
Login as nonprofit user: testnonprofituser2@gmail.com / Opensource5social!
Click on Opportunities
Click on an opportunity name

**Requirement**
1. Delete button: Popup Are you Sure. Upon Yes, call Rest API to delete the project
2. Redirect to Project List page (don't stay on the same project view page after deletion).  Verify the project is not showing up.

**Comment by chaitanyas16** [comment]
The above changes done in the pull request #438 .
