### ISSUE TITLE
Project/Organization/User Pages: Retrieve skills tag

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#302]
- **Web Path**
Page 1. Click Opportunities: skills tags for each opportunity
Page 2. Click Opportunities -> Click an opportunity: skills tags for the opportunity in middle panel, and opportunities in right panel
Page 3. Click Volunteers: skills tags for each user
Page 4. Click a volunteer: skills tags for the user
Page 5. Click Organizations -> click and organization: skill tags in the right panel 

- **Requirement**
For these five pages, retrieve the skills from backend for either project or user, and display. 
Endpoints: GET /api/skills/project, GET /api/skills/user
Currently the skill tags are hard coded.

**Comment by SathiyaNeve** [comment]
Changes Committed

**Comment by chaitanyas16** [comment]
Changes made as per the issue for pages 1,2,3 and 4 in pull request #362 . The page 5 is already showing expected results so changes done.
