### ISSUE TITLE
User Edit Page - Display

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#325]
- **Web Path**
Login as volunteer user: testvolunteeruser2@gmail.com / Opensource5social!
Click User Name -> My Settings

- **Requirement**
1. Phone: only display this field if login user is nonprofit user
2. My profile section: only display this section if login user is volunteer user
3. Publish my profile & Notify my for opportunities match my skills: If backend returns 'N', uncheck. If backend returns 'Y', check. Please reference remote/local button in Project Edit Page on how to implement.
4. Skill section: implement the same as Project Edit page

- **Reference: Project Edit page** 
1. Login as admin user: mydummytest1@gmail.com / dummypassword, 
2. Click Opportunities
3. Click a project

**Comment by chaitanyas16** [comment]
Submitted a pull request for changes 1 to 3. Currently working on change 4.
