### ISSUE TITLE
Volunteer User - Few Opportunities description details showing incorrect content.

### ISSUE THREAD

**Issue by sreelatha6** [Code4SocialGood/c4sg-web#332]
Login as Volunteer User, URL - http://dev.code4socialgood.org/.
Click on Opportunities Menu
Click on Graphic Designer Opportunity. (7th Opportunity in default listing page)

Description Content showing some incorrect content in it around 6th line
below is actual content now showing.
<img width="805" alt="graphicdesigner_opportunitydescription had invalid data in it" src="https://cloud.githubusercontent.com/assets/28464814/26280587/e58c6672-3da7-11e7-9105-f553abc2e398.PNG">

This is the social enterprise data harvesting for impact hackathon. There are multiple sections of the hackathon you can help in. This volunter opportunity focuses on finding go-tomarket challenges of the social enterprise sector within this data set. https://docs.google.com/spreadsheets/d/1ttZLft3kWpPZcW4uCJwL57_Vs9nZmfXuaTh1yfxRQ0I/edit?usp=sharing. Terms and condtions of volunteering can be found here (www.advancesocialinnovation.org and here: https://docs.google.com/forms/d/1P-DMefgQCaH7p1u_9Hgl6BSFEN9pC6NDs_onxoaVgMc/edit?ts=57ccc12a. The goal is to label and harvest data from twitter on social enterprise so that we can create maps of resources that existin the sector for social enterprises.

**Comment by Code4SocialGood** [comment]
We only display 3 lines of description. This issue is not able to be recreated.
