### ISSUE TITLE
Volunteer User - Organizations Menu, Multiple instances of same organisation showing

### ISSUE THREAD

**Issue by sreelatha6** [Code4SocialGood/c4sg-web#333]
Login as Volunteer User, URL - http://dev.code4socialgood.org/.
Click on Organizations Menu
Enter "Test" in Keyword search and click on searchmirror icon

9 organizations found shows.
It seems "Museum of Modern Art"  showing 8-9 times.

Not sure if it is same instance showing multiple times or different instances .
something incorrect here.
<img width="839" alt="museum of modern art_showing 9-times" src="https://cloud.githubusercontent.com/assets/28464814/26280652/813e6540-3dab-11e7-9650-57d7008f784a.PNG">

**Comment by Code4SocialGood** [comment]
Organizations are show multiple times because there are multiple records on database with duplicate data. The data is fixed. Please re-test.

**Comment by sreelatha6** [comment]
Verified the Fix,
 I am seeing the issue fixed correctly, I don't see multiple organisations anymore now.
Thanks for Fixing it, .
