### ISSUE TITLE
Project List: Filter by Skill does not revert to ALL Projects when skills are unselected

### ISSUE THREAD

**Issue by rituven** [Code4SocialGood/c4sg-web#339]
Select a couple skills in the left frame of Project List page. The list of projects narrows down to only those projects that contain the Skills selected. Now unselect the skills. No Projects are displayed anymore. The page should default back to ALL projects when all skills are unselected.

**Comment by chaitanyas16** [comment]
The projects are shown as expected. Please check and confirm.

**Comment by rituven** [comment]
Retested the functionality and it seems to work now. Closing the issue.
