### ISSUE TITLE
Volunteers Menu is showing without user Logging in

### ISSUE THREAD

**Issue by sreelatha6** [Code4SocialGood/c4sg-web#344]
Access -http://dev.code4socialgood.org/
Volunteers Menu shouldn't be displayed if  user(Admin or NonProfit User)  is not logged in.

Step 13  from TestCase Document
A user who has not logged into the system cannot access the User List Page.

<img width="695" alt="userlist_testcase_step13" src="https://cloud.githubusercontent.com/assets/28464814/26327516/c182ebe0-3f0d-11e7-8629-ed01808d4d2f.PNG">
<img width="700" alt="volunteersmenushowing-without loggingin" src="https://cloud.githubusercontent.com/assets/28464814/26327612/1177b338-3f0e-11e7-9185-601c2865f104.PNG">
<img width="681" alt="homepage_volunteersmenu_withoutlogged in" src="https://cloud.githubusercontent.com/assets/28464814/26327624/1ad3ddf8-3f0e-11e7-904e-8dc8612ce139.PNG">

**Comment by Code4SocialGood** [comment]
Please see issue #345. 
Please close this issue.
