### ISSUE TITLE
Volunteers Menu is showing for user type account - volunteer user.

### ISSUE THREAD

**Issue by sreelatha6** [Code4SocialGood/c4sg-web#345]
Access C4SG website with URL  - http://dev.code4socialgood.org/.
Login to website as Volunteer User.

On Top Menu Bar, Volunteers menu is showing.
Volunteers menu should be available only for Admin or Non-profit Users(after they logged in)
 but not for Other Volunteers Users.
<img width="955" alt="volunteers menu showing for usertype volunteer users" src="https://cloud.githubusercontent.com/assets/28464814/26357600/ca7ee466-3f9d-11e7-9973-8afe85c9600d.PNG">
<img width="719" alt="testcase_step 14" src="https://cloud.githubusercontent.com/assets/28464814/26357649/f03bc688-3f9d-11e7-84a6-c1d2a3b2fc12.PNG">

**Comment by Code4SocialGood** [comment]
- **Business Requirement**
1. Volunteers menu is available for public access. 
2. Volunteer list page shows uses that are:
- with "volunteer" role (there are 4 roles in this app: volunteer, nonprofit, admin, public)
- marked "Publish My Profile" as yes (this is a checkbox on User Settings page)
- with "active" status (when a user is deleted, we don't physically delete them from database, we change their status to "deleted" instead, this way we can keep the history log) 
- order by joined date in descending order (please provide your input here, should we order by join date or should we order by username in alphabetic order?)

- **Action Items**
- Study this web site to see if we missed any feature in our use case, https://www.upwork.com/o/profiles/browse/
- Determine how to order users on the result list
- Update Business Requirement document
- Update Test Case Document
- Update/Close this issue

**Comment by rituven** [comment]
When you say 'there are 4 roles in this app: volunteer, nonprofit, admin, public', how is the 'public' role defined? Is a user who has not logged in or has not registered, classified as having a 'public' role?

**Comment by Code4SocialGood** [comment]
public user is user who has not registered or has not logged in to our web site. We can't distinguish whether the user is not registered or not logged in. 

So, let's define public user as "User not logged in".

**Comment by rituven** [comment]
BRD has been updated.

**Comment by sreelatha6** [comment]
as per Jenny's clarification, Volunteers menu showing fine for all user types, no issues now.
I have updated Test Case and sent to Ritu to upload. as I don't see permission on this doc to edit.
