### ISSUE TITLE
Organization List Page - Search

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#352]
Click Organizations 
Search by Projects doesn't work.
Search by Category doesn't work. 
Please reference Project List page on how the search should work.

**Comment by parloti** [comment]
@Code4SocialGood   front end expects

`{
  content:[{organization}/* max 10 objects*/]
  totalElements: /* max 10*/]
}`

but back end is returning

`[{organization}/* 22 objects*/]`

http://localhost:8080/api/organizations/search?status=A&page=0&size=10

Apparently related issue:
https://github.com/Code4SocialGood/c4sg-services/issues/226

**Comment by Code4SocialGood** [comment]
Backend endpoint seems working fine. Try on test server: 
http://dev-api.code4socialgood.org/swagger-ui.html#!/organization/getOrganizationsUsingGET

Backend endpoint was refactored 3 days ago. Please check whether you have the latest code on backend. 
https://github.com/Code4SocialGood/c4sg-services/pull/231

![image](https://user-images.githubusercontent.com/24813620/27385085-fe5d27e6-5656-11e7-945e-a817bc6073d4.png)

![image](https://user-images.githubusercontent.com/24813620/27385097-0d0fb1dc-5657-11e7-907f-8536d07b52f3.png)

**Comment by parloti** [comment]
_**Search by Category doesn't work.**_
In http://dev-api.code4socialgood.org/swagger-ui.html#!/organization/getOrganizationsUsingGET
If category is not empty, the server will return error 500.
