### ISSUE TITLE
User List Page: Skills not displayed in the User 'cards'

### ISSUE THREAD

**Issue by rituven** [Code4SocialGood/c4sg-web#358]
Skills are not being displayed in the User profiles in the User List page.
![screen shot 2017-05-24 at 12 00 37 pm](https://cloud.githubusercontent.com/assets/12638803/26420806/a705796a-4078-11e7-92af-89b19639f2a4.png)

Per issue #298, the users' skills should be displayed under their title.

**Comment by chaitanyas16** [comment]
Changes made for this issue is pull request #362.
