### ISSUE TITLE
Home Page - Add Background for Drop Down Menu

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#382]
The drop down menu has transparent background and hard to read. Please add a grey background. 

![image](https://user-images.githubusercontent.com/24813620/27165716-6c0ac132-515b-11e7-88be-3084f6178d8b.png)

**Comment by davidherszenhaut** [comment]
What color should the dropdown be?

**Comment by Code4SocialGood** [comment]
When user is on home page and click the drop down, the menu items are always grey.
If you click Projects, then click the drop down, the active menu item change color when mouse hover. 
Please make the drop down on home page change color for active menu item.

See example:
1. Materialize (this is the css framework we are using): 
    http://materializecss.com/dropdown.html
2. Angular 2 Materialize (this is the plug-in we are using so that materialize could work in Angular 2 environment): 
    http://angular2-materialize.surge.sh/#/Dropdown

![image](https://user-images.githubusercontent.com/24813620/27202786-86496764-51e8-11e7-9004-55b4b8e3f60b.png)

![image](https://user-images.githubusercontent.com/24813620/27202803-9e3046f4-51e8-11e7-9dcf-403f2979dd87.png)
