### ISSUE TITLE
Header - Add Logo above menu items

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#386]
1. Make the menu item black color instead of green.
2. Add logo above the active menu item.
3. See wireframe below.
3. Logo image is attached below.

[](![image](https://user-images.githubusercontent.com/24813620/27165635-ef2794ba-515a-11e7-9975-9d3d0162e310.png))

![greenchain](https://user-images.githubusercontent.com/24813620/27165670-24cd15a4-515b-11e7-9790-7d0ef4006654.png)

**Comment by Midnightapplepie** [comment]
is there a reason why the header links are using onclick that trigger router.navigate(...) instead of routerLink='/url/' ? new to Angular, curious

**Comment by Code4SocialGood** [comment]
The chain works well in project/organization/volunteer list pages. 
Please add to the follow pages as well:
1. project/organization/volunteer view pages
2. project/organization/volunteer edit pages (you need to login as admin user and click the Edit button: mydummytest1@gmail.com / dummypassword)

![image](https://user-images.githubusercontent.com/24813620/27512341-4444fccc-5902-11e7-80e1-f495e10203de.png)

![image](https://user-images.githubusercontent.com/24813620/27512343-4fd0b04a-5902-11e7-9376-5449281f572f.png)

**Comment by Code4SocialGood** [comment]
Resolved in PR #574
