### ISSUE TITLE
Project Create Page - Project Notification

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#395]
When a new project is added, send an email notification to the user.

**Comment by parloti** [comment]
Should not this be a backend?
From the front end I can only send the data to the server which in turn will do the sending.

**Comment by Code4SocialGood** [comment]
You are correct. This issue should be moved to backend, implemented in the create project endpoint.

**Comment by Code4SocialGood** [comment]
Close this issue from frontend.
Created an issue at backend: https://github.com/Code4SocialGood/c4sg-services/issues/242
