### ISSUE TITLE
Create Organization Page - Display

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#40]
- **Web Path**
Home
Login as admin user: mydummytest1@gmail.com / dummypassword
Create Organization

- **Requirement**
1. Input fields: animate the label (label moves up when you click on the input)
2. Remove Green and Red validation states
3. Remove icon on the label (Website, email, phone)
4. User standard "*" for mandatoru fields
5. City on top of State
6. State: remove drop down, make it a textfield
7. Category drop down: Add "Open Source", "Other" after Nonprofit
8. Take out Short Description
9. Long Description: change to "Description" , and, make it span two columns
10. Create button: in the middle of the page

- **Reference**
http://materializecss.com/forms.html

**Comment by praveenaraoa** [comment]
This Page is already created by someone else. Validations, routing is also done for this page. nonprofit/create.

**Comment by Code4SocialGood** [comment]
Yes, the page already exist, Please modify the page display as described in the requirement.

**Comment by praveenaraoa** [comment]
I finished almost everything in this requirement. I have a question about"1. Input fields: animate the label (label moves up when you click on the input)". 
1. Do you want the task to be done using animations? or css? if css: the label should be inline initially?

**Comment by Code4SocialGood** [comment]
Input fields should be done using css, the label should be inline initially. Similar as in Opportunities page (http://dev.code4socialgood.org/project/list), when you click on the Keyword.

**Comment by praveenaraoa** [comment]
Yes. Thank you. I did using css. Thank you for confirming.

**Comment by Code4SocialGood** [comment]
Create Organization page is to be deleted
