### ISSUE TITLE
Project View Page - Apply Button - Login before Apply

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#402]
1. Click Opportunities
2. Click a project
3. Click Apply
System response: Toast is throw: please login to apply; Auth 0 window is popup
Problem: The toast can hardly be noticed by user due to the Auth0 popup at the same time
**Change Request: Change the toast to tooltip: Login to Apply**
4. Login
5. Click Apply
System response: Apply to project is performed successfully.
Problem: No toast is thrown (if you are already logged in when you click Apply button, the toast is throw correctly)
**Change Request: Throw toast**

**Comment by joshisayali** [comment]
I will look into it

**Comment by Code4SocialGood** [comment]
Click Opportunities
Click a project
Click Apply
Auth 0 window is popup
Login:  testvolunteeruser2@gmail.com / Opensource5social!

**Apply and Bookmark buttons disappeared**

![image](https://user-images.githubusercontent.com/24813620/26904919-04233178-4baa-11e7-96f5-e58c74c9bbf5.png)
