### ISSUE TITLE
Home Page - Drop Down Menu Disappears

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#417]
The drop down menu disappears when user tries to select the menu option.

See some reference here: https://stackoverflow.com/questions/14863044/css-hover-drop-down-menu-disappears-when-trying-to-select-menu-option

**Comment by parloti** [comment]
It seems that this problem has already been solved.
I have tested it in several browsers and the menu has not disappeared.

**Comment by Code4SocialGood** [comment]
Thank you for test this issue. Yes, the issue seems gone. I am closing this issue.
