### ISSUE TITLE
Load of page content

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#458]
When a page is loaded, the content is not fully displayed unless user refreshes the page. Even the menu is not displayed.

![image](https://user-images.githubusercontent.com/24813620/27149901-d14a9b40-510a-11e7-92e2-94fd459ad8fc.png)

**Comment by gugui3z24** [comment]
This is happening due to issues with Raleway font. Modifying the font size or weight in the page-title CSS class causes this error. Current fix is to use Google Font import instead of local font. See solution at: https://github.com/Code4SocialGood/c4sg-web/tree/BranchIssues458

**Comment by Code4SocialGood** [comment]
Could you please submit a PR from the branch? We will review and merge the PR after it passes Travis build. 

FYI, we are in the process of setup Heroku pipelines so that each PR will trigger a deployment to the test server. The PR will be validated on the server without code reviewer fetch it and run it in his local environment.
