### ISSUE TITLE
Share Button - Share to Twitter

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#491]
- **Requirement**
Click Projects
Click a project
Click Share -> Twitter
Share the project to Twitter

- **Reference**
Volunteer Match
Idealist

**Comment by parloti** [comment]
@rxc101 #490 #491 #492 are very related.
If you had not already started, I'd like to solve this out.

**Comment by rxc101** [comment]
No problem, thanks

**Comment by Code4SocialGood** [comment]
Resolved in PR #755
