### ISSUE TITLE
Share Button - Share to Email

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#493]
- **Requirement**
Click Projects
Click a project
Click Share -> Email
Share the project to email

- **Reference**
Volunteer Match
Idealist

**Comment by Code4SocialGood** [comment]
@parloti Would you like to take a look at this share button issue, similar to the other share button issues you resolved? 

Reference: https://www.idealist.org/en/volunter-opportunity/305921f2dc644e8288025d8ba48e033c-grant-writing-team-the-social-cultural-movement-for-haitian-workers-villa-mella

**Comment by parloti** [comment]
Sorry for not mentioning it in PR #755, but I implemented it too.

But I can easily implement changes regarding the subject or body of the message.

**Comment by Code4SocialGood** [comment]
Issue Resolved in PR #755.
