### ISSUE TITLE
Skill Tags - Change to grey color

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#494]
- **Requirement**
Change the skill tags to light grey background with dark grey font color.

- **Web Pages that have skill tags**
Login as admin user: mydummytest1@gmail.com / dummypassword
1. Project List Page: Click Projects
2. Project View Page: Click Projects -> Click a project
3. Project Edit Page: Click Projects -> Click a project -> Click Edit button
4. Volunteer List Page: Click Volunteers 
5. Volunteer View Page: Click Volunteers -> Click a volunteer
6. Volunteer Edit Page: Click Volunteers -> Click a volunteer -> Click Edit button
7. Organization View Page: Click Organizations -> Click an organization with projects -> right panel has the skills tag

- **How the skill tags should look like**
![image](https://user-images.githubusercontent.com/24813620/27263042-274c8902-5428-11e7-8916-dcabcb40de84.png)

**Comment by chetoos** [comment]
Where the hell do I go to do this? I've been trying to figure out where to go on the git, but can't find anything

**Comment by Code4SocialGood** [comment]
Have you setup the local dev environment and have the frontend running locally?

**Comment by chetoos** [comment]
I have not, but I also don't know which file to go into to change the skill tags.

**Comment by Code4SocialGood** [comment]
Please setup local dev, and run the app to find out the files to change.

**Comment by Code4SocialGood** [comment]
After discuss with the designer, we decided to keep the existing color of green for the skill tags. This issue is closed.
