### ISSUE TITLE
Travis CI on Frontend

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#5]
_From @Code4SocialGood on March 11, 2017 23:27_

Travis CI has been integrated with backend.
Frontend developer wanted to help with frontend integration.

_Copied from original issue: Code4SocialGood/C4SG#506_

**Comment by russon77** [comment]
## todo

- [ ] configure surge deployment in travis

**Comment by russon77** [comment]
we did it!
