### ISSUE TITLE
Add Feedback Feature

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#506]
1. Add a Feedback button on the left side of the web page (ideally every page on the web site). User orange color: #ff4f00
2. Click the Feedback button will open a new browser to this page: http://forum.code4socialgood.org/c/site-feedback
3. Allow user to post to this site-feedback category as anonymous user, without login. You may need login to forum site as admin user to configure it.
4. Customize the forum header to make it C4SG look and feel (with C4SG logo, etc). You may need login to forum site as admin user to configure it.

Reference: Catch A Fire, https://www.catchafire.org/

**Comment by parloti** [comment]
Where is this repository?

**Comment by Code4SocialGood** [comment]
@parloti Sorry missed your question. It is the forum, http://forum.code4socialgood.org/
