### ISSUE TITLE
LATER - Social Media - Blog

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#52]
Requirement: Setup up blog

**Comment by russon77** [comment]
i think using a tumblr (with custom domain, i.e. pointing it to blog.code4socialgood.org) is common. what type of blog are we seeking?

**Comment by Code4SocialGood** [comment]
Another option is medium.com. It requires login to the blog site. No SSO from C4SG to medium.com blog site.
Reference: https://medium.freecodecamp.com/
