### ISSUE TITLE
Remove extra border

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#520]
**Pages**
- Project View Page
- Volunteer Page
- Organization View Page

**Requirement**
Remove the extra border on bottom of the right panel

![image](https://user-images.githubusercontent.com/24813620/27421239-2a661af8-56ef-11e7-9cd6-abd3b15be355.png)
![image](https://user-images.githubusercontent.com/24813620/27421250-35729c50-56ef-11e7-80ee-1fbcb1f6358c.png)
![image](https://user-images.githubusercontent.com/24813620/27421269-4b009a0e-56ef-11e7-9d42-7d9d5782f8f5.png)

**Comment by mechachi** [comment]
Fixed and merged.
