### ISSUE TITLE
Social Media - Forum

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#53]
_From @Code4SocialGood on January 6, 2017 15:48_

Tool: Discourse
Hosting: Amazon AWS

_Copied from original issue: Code4SocialGood/C4SG-Obsolete#77_

**Comment by russon77** [comment]
found:

https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md

**Comment by russon77** [comment]
http://ec2-54-213-179-34.us-west-2.compute.amazonaws.com/

## done

- [x] ec2 instance created
- [x] discourse installed

## todo

- [ ] configure email
- [ ] configure dns
