### ISSUE TITLE
Drop Down Menu

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#552]
Login as nonprofit user: testnonprofituser2@gmail.com / Opensource5social!
Click on the top right drop down menu
"My Organization" menu item is split into two lines.
Please shift the menu items to the left side a little bit, so that "My Organization" fit in one line

![image](https://user-images.githubusercontent.com/24813620/27512594-57793cd2-590b-11e7-82dc-d11049bdde5b.png)

**Comment by axlemax** [comment]
Could you describe the browser and possibly window size? For me in Chrome and Firefox "My Organization" is always on one line.

**Comment by Code4SocialGood** [comment]
It is on one line for me as well.
Let's close this issue for MVP release. We will review it in later release when we consider cross browser support and responsiveness design.

![image](https://user-images.githubusercontent.com/24813620/28235314-289d52a6-68d1-11e7-84e1-f30b5be32d04.png)
