### ISSUE TITLE
My Settings - Animation for Input Field Labels

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#559]
Login as volunteer user: testvolunteeruser2@gmail.com / Opensource5social!
Click from top right drop down: My Settings
If there is no value for a input field, the label should be right above the underline. When use click the label, label shifts up.
See: http://materializecss.com/forms.html

- **Sample Input Field in Materialize CSS**
![image](https://user-images.githubusercontent.com/24813620/27513015-2a530e7a-591c-11e7-9bc6-58a7c8e50fa4.png)

- **Screen shot of Current Page**
![image](https://user-images.githubusercontent.com/24813620/27513009-a2c7707c-591b-11e7-8168-bdb62bb6034b.png)

**Comment by axlemax** [comment]
I have a PR ready - although the Summary area still is kinda weird to me, it is being displayed as it should according to Material guidelines for multi-line text fields.

**Comment by axlemax** [comment]
Ok, should be fixed now.

**Comment by Code4SocialGood** [comment]
Resolved in PR #630.
