### ISSUE TITLE
Underline for Input Fields

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#560]
Login as volunteer user: testvolunteeruser2@gmail.com / Opensource5social!
Click from top right drop down: My Setting
Click an input field, the underline is changed to Blue color.
Please research on how to change the underline to green color: $secondary-bg-color
Note: this change should be applied to all text fields in the application

**Comment by axlemax** [comment]
Will combine this and #662 to create a green revolution.

**Comment by Code4SocialGood** [comment]
Resolved in PR #680
