### ISSUE TITLE
Restrict skill tags to be max of 10

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#567]
Login as admin user: mydummytest1@gmail.com / dummypassword
1. Click Projects -> Click a project -> Click Edit
1. Click Volunteer -> Click a volunteer -> Click Edit

In the above two pages, user could add skill tags. Please restrict the tags to be maximum of ten. If use try to select from drop down or add an entered value after ten is reached, throw an error message in toast. Please reference how toast is thrown when user tries to add a skill that is already on the list. 

![image](https://user-images.githubusercontent.com/24813620/27513510-4dcef79e-592e-11e7-8d21-457c6cc8b198.png)

**Comment by chaitanyas16** [comment]
Changes done in PR 576.
