### ISSUE TITLE
My Settings - Summary Textarea

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#572]
Login as volunteer usesr: testvolunteeruser2@gmail.com / Opensource5social!
Click from top right drop down: My Settings
Summary is a text area. The input space will expand as user enters more text. Make the initial space one line so that the web form look more concise. Currently the initial space for this field is 3 lines.

![image](https://user-images.githubusercontent.com/24813620/27517359-cedf86e8-5990-11e7-8a16-d2e65bc096f3.png)

**Comment by chetoos** [comment]
finished

**Comment by Code4SocialGood** [comment]
Resolved in PR #727 .
