### ISSUE TITLE
Mouse Over Icon - Change to Green Color

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#582]
Login as admin user: mydummytest1@gmail.com / dummypassword
Click Volunteers
Click Volunteer
When mouse over **non-disabled** icons, change the icon background to $secondary-bg-color

![image](https://user-images.githubusercontent.com/24813620/27521710-8e7ce064-59e5-11e7-8f82-dcd79b1e7344.png)

**Comment by chetoos** [comment]
I think I worked this out, but my personal server isn't working right. Can someone test this CSS file for me?
[New WinRAR ZIP archive.zip](https://github.com/Code4SocialGood/c4sg-web/files/1102417/New.WinRAR.ZIP.archive.zip)

**Comment by Code4SocialGood** [comment]
Are you running only the frontend locally? What is the error?

**Comment by chetoos** [comment]
I tried to run the server locally, but when I ran the apache and went to localhost, all I got was a blank white screen. I followed all the instructions to have the local server direct to the index page in src

**Comment by Code4SocialGood** [comment]
Did you get any error in the command window that start the server?

**Comment by chetoos** [comment]
No error, I run Apache from the httpd file in the bin folder directly, just double clicking it.

**Comment by chetoos** [comment]
I just did a test to make sure that it was loading the right file, the one I pointed it to, and it is, but the index.html file seems to have nothing on it, so I can't use it to go through the local server

**Comment by Code4SocialGood** [comment]
@axlemax Unfortunately, this issue was not resolved with PR #752. I tested both locally and on dev server after PR merge.

If you view a sample user: http://dev.code4socialgood.org/user/view/11, the icon doesn't change color with mouse hover. 

I even tried remove the conditional check in the code block before, the .mdi:hover didn't change icon color.

// Make social media links colored when hovering
.mdi:hover   //:not(.not-active) {
 color: $secondary-bg-color;
 }

**Comment by axlemax** [comment]
Ok, I'll check it out, thanks for letting me know!

**Comment by Code4SocialGood** [comment]
Resolved in PR #793
