### ISSUE TITLE
Bookmark do not prompt to login.

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-web#602]
Step to Reproduce
1. Organization->Select a project->Click on Apply-:Login is prompted.
BUT
2. Click on Bookmarks->"Login to Bookmark" Mouse over text is there but Login is not Prompted.

Expected Result:
Bookmark should prompt to Login page when clicked on.

![project apply](https://user-images.githubusercontent.com/29553195/27651261-b44c118a-5c05-11e7-81f8-c356644cd30e.jpg)

**Comment by Code4SocialGood** [comment]
Resolved in PR #625
