### ISSUE TITLE
Applied/Bookmarked Projects

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#611]
1. Login as volunteer user
2. (Optional implementation) 
Click Projects: for applied or bookmarked projects, display Apply or Bookmark tag on top right corner
3. (Required implementation) 
Click a project: for applied or bookmarked project, , display Apply or Bookmark tag on top right corner, and, disable the Apply/Bookmark button accordingly

Due to the implementation challenge and performance concern, please implement the logic in frontend:
1. When volunteer user login: 
- Call GET /api/projects/user to get applied and bookmarked projects for the user
- Save the appliedProjectIDs and bookmarkedProjectIDs in local storage/sesssion for the user
2. When click Projects
- Retrieve the projects as usual
- For each project, check whether the project ID is in the list of appliedProjectIDs or bookmarkedProjectIds
- If yes, display apply/bookmark tag accordingly
3. When click a project
- Retrieve the project as usual
- Check whether the project ID is in the list of appliedProjectIDs or bookmarkedProjectIds
- If yes, display apply/bookmark tag accordingly, and, disable the apply/bookmark button

**Comment by parloti** [comment]
https://github.com/Code4SocialGood/c4sg-web/commit/9aef7568992522e21dd7c1296af58d01591e92ad#commitcomment-22924593
