### ISSUE TITLE
Search by Role - User & Project

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#635]
Pages: Project List Page & Volunteer List Page 
Implement Search by Roles on the sidebar.
1. Roles are radio buttons
2. List of roles should be retrieved from backend: 
GET /api/projects/jobTitles
GET /api/users/jobTitles
3. After user click radio button, the corresponding jobTitleID is passed as parameters to search endpoint

![image](https://user-images.githubusercontent.com/24813620/27897142-109f6070-61e4-11e7-91ce-7b2e9f9c48bc.png)

**Comment by chaitanyas16** [comment]
Changes done for Project List in in PR#757, Working on User Project Role.

**Comment by chaitanyas16** [comment]
Changes done to User List in PR#775.
