### ISSUE TITLE
Null Landing Page Search Returns Empty Project Page

### ISSUE THREAD

**Issue by bshores** [Code4SocialGood/c4sg-web#648]
**Description:**
As a user when I navigate to the home page, if I enter nothing into the search box on the land page, and click the search icon, I should get a default view of all projects. 

**Assumptions:**
The user in test is not logged into the application

**Test Case:**
1. Navigate to the home landing page
"http://dev.code4socialgood.org"
2. Do not enter anything into the search criteria box 
3. Click the search icon

**Expected Result:**
The user should be taken the project link, and display all open projects that are available

**Actual Result:**
The user is taken to a blank projects page

**Possible fix:**
When performing this, I notice the url takes the user to http://dev.code4socialgood.org/project/list/home
To assist in the behavior above the url should be directed here if the search criteria has a null entry http://dev.code4socialgood.org/project/list/projects

**Comment by Code4SocialGood** [comment]
@bshores Issue is resolved in PR #657. Please test.

**Comment by bshores** [comment]
Retested. Now working.
