### ISSUE TITLE
Enter Key Main Search Does not Work

### ISSUE THREAD

**Issue by bshores** [Code4SocialGood/c4sg-web#649]
**Description:**
As a user when I navigate to the home page, when i enter a search criteria and select enter it should bring me to the project page associated with the context of the search 

**Assumptions:**
The user in test is not logged into the application

**Test Case:**
1. Navigate to the home landing page
"http://dev.code4socialgood.org"
2. Enter search criteria into the search box
3. Strike the "Enter" key on your keyboard

**Expected Result:**
The user should be taken the projects page performing the search that is being requested

**Actual Result:**
The enter key is not functioning in this search box

**Environment:**
Google Chrome Version 58.0.3029.110 (64-bit)
MacOSX - Sierra

**Comment by Code4SocialGood** [comment]
Adding comments: 
ENTER key does not work. Search Icon works as expected.
Please make ENTER key behave the same as Search Icon.

**Comment by Code4SocialGood** [comment]
This issue is resolved in PR #653. 
@bshores Please test then close this issue.

**Comment by bshores** [comment]
Now working.
