### ISSUE TITLE
Skills not Saving to user when added

### ISSUE THREAD

**Issue by bshores** [Code4SocialGood/c4sg-web#673]
**Description**:
As a user when I create a new user, and add a skill. After I click save the skill should be saved to that user for later use. 

**Assumptions**:
No user Created

**Test Case:**

1. Create a new user, verify email.
2. Login using the newly created user
3. Click dropdown for the user in the top right
4. Click My Settings
5. Under my skills, add skills from the drop down menu Example I selected Ruby
6. Click save

**Expected Result:**
Adding a skill to my user should save, after clicking the save button. 

**Actual Result:**
When navigating back to the volunteer screen the added skills do not show up. When going back into my settings, the skills never successfully saved to the user profile

**Comment by Code4SocialGood** [comment]
This is the same issue as #672. #672 and #673 will be fixed in one PR.

**Comment by Code4SocialGood** [comment]
@bshores This issue is resolved in PR #703. Please retest.

**Comment by Code4SocialGood** [comment]
Issue is resolved in PR #703.
