### ISSUE TITLE
View Project Page - Apply for Project

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#68]
_From @Code4SocialGood on February 9, 2017 18:45_

Home Page -> Projects -> Click a Project
1. Add a button with label "Apply"
2. When apply button is clicked, calls Rest API (backend task is #111 ).
3. Generate a toast notification: "You have applied the project." See: http://materializecss.com/dialogs.html

_Copied from original issue: Code4SocialGood/C4SG-Obsolete#219_

**Comment by sandunr** [comment]
Hi Jenny!! Can I get assigned to this task?
Thanks.

**Comment by Code4SocialGood** [comment]
Hi Sandun, I apologize that I missed your comment. The task is assigned to you.
