### ISSUE TITLE
About Use Page - Mouse out user profile

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#707]
When move out user pointer, please hide the user profile.

![image](https://user-images.githubusercontent.com/24813620/27981044-4bc880f6-634b-11e7-809e-5e7e2b818bf0.png)

**Comment by Midnightapplepie** [comment]
do you want info-window to close on event mouseout on the marker on google map?
the info window is a link to user's profile page, close window on mouseout on the marker will prevent any interaction with the user profile link. 

if you mean close info-window on mouseout on the info-window, that is kind of weird UI, let me know.

**Comment by Code4SocialGood** [comment]
"I am thinking to allow only one active window so when user hover to a new marker, previous window will close"...

**Yes, that works! Please make the change. Thanks.**

**Comment by Code4SocialGood** [comment]
PR #711 merged. Works great.
