### ISSUE TITLE
The Edit and Save Project doesn't work

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-web#732]
Step to Reproduce:
1.Login as nonprofit user: testnonprofituser2@gmail.com / Opensource5social! or Admin user mydummytest1@gmail.com / dummypassword
2. Click from drop down: My Projects
3.Select Test Project and click on Edit

There are 2 issues here:
1. If user is selecting to edit an existing test description, previous description should be available to update, here its not should previous texts.
![edit project](https://user-images.githubusercontent.com/29553195/28025426-64c2a218-6561-11e7-9ee0-57d168c1d742.jpg)
2. After update user is not able to SAVE.

**Comment by Code4SocialGood** [comment]
This issue is resolved, please retest

**Comment by p-tal** [comment]
User is able to see and update and Save project from Edit project. Retest passed. Defect ok to close.
