### ISSUE TITLE
Edit Project: Project name and Description has "overlay" text

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-web#746]
Step to Reproduce:

1.Login as nonprofit user: testnonprofituser2@gmail.com / Opensource5social! or Admin user mydummytest1@gmail.com / dummypassword 
2. Click from drop down: My Projects 
3.Select Test Project and click on Edit.
4. The Project Name and description has over lay text. Please see screenshot for more details.

![edit project_overite](https://user-images.githubusercontent.com/29553195/28071171-2780ff6e-661d-11e7-8004-5e2e3ce1f103.jpg)

**Comment by Code4SocialGood** [comment]
Resolved in PR #795
