### ISSUE TITLE
My setting Page : Values not showing in IE

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-web#758]
Steps to reproduce:
Browser: Internet Explorer
1. Login using volunteer user: testvolunteeruser2@gmail.com / Opensource5social!
2. Go to My settings page.
3. Verify details:
Actual result: User details are not shown in IE browser where as its showing up fine in Chrome.
NOTE: This issue is with other pages like My Projects too in IE.
Please see screenshots for more details.
![mysettingie](https://user-images.githubusercontent.com/29553195/28185265-c17d5220-67e4-11e7-9672-3081d1e26393.jpg)
![mysettingchrome](https://user-images.githubusercontent.com/29553195/28185276-c624083c-67e4-11e7-9551-4d4a26a2a394.jpg)
![myproject ie](https://user-images.githubusercontent.com/29553195/28185316-ddd0c3bc-67e4-11e7-81cd-0c45620ecf36.jpg)

**Comment by Code4SocialGood** [comment]
Can't recreate the problem. Close this issue.

**Chrome**
![image](https://user-images.githubusercontent.com/24813620/28501275-334b8d0c-6f9e-11e7-93f6-48be7b22ded4.png)

**IE**
![image](https://user-images.githubusercontent.com/24813620/28501278-48b843d8-6f9e-11e7-99ed-ce37221765ac.png)
