### ISSUE TITLE
My Projects - Add border

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#792]
Login as volunteer user:  testvolunteeruser2@gmail.com / Opensource5social!
From drop down, click My Projects
1. Please add a border to the panel.
2. Please change page title from Projects to My Projects.

![image](https://user-images.githubusercontent.com/24813620/28233706-4a39969e-68be-11e7-81cd-2971b2e986ce.png)

![image](https://user-images.githubusercontent.com/24813620/28233537-24e7d7f8-68bd-11e7-959f-6b64abcb4e5a.png)

**Comment by axlemax** [comment]
What style do we need the border to be? (color, thickness, etc.)

**Comment by Code4SocialGood** [comment]
@axlemax It should be the same as other borders, like the one shown below in Create Project page.

![image](https://user-images.githubusercontent.com/24813620/28235354-c2df22f4-68d1-11e7-813d-e99c9b734690.png)

**Comment by Code4SocialGood** [comment]
Resolved in PR #854
