### ISSUE TITLE
Change Request: Please add more details for Nonprofit users for approval of New Organizations.

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-web#811]
Change Request details: Can you please add more specific details to make a non profit users understand that ADMIN will approve their Organization.
They can view their Organization details only when admin users approves it.

**Comment by Code4SocialGood** [comment]
When organization is new, display text in My Organization: Please complete My Organization information. Your organization will be reviewed before you can post projects.

When organization is under review, display text in My Organization: Your organization is under review. You will be able to create project after your organization is approved. We will notify you as soon as possible.

**Comment by Code4SocialGood** [comment]
@p-tal This issue is resolved, please retest.

**Comment by p-tal** [comment]
Retest successful. Defect ok to close
