### ISSUE TITLE
Misaligned Apply-Decline Button in My Project|| Environment Stage

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-web#831]
Environment : Stage
1. Login as a non profit user: StageNonProfitUser@gmail.com   Mycode@11
2. Click on a Project from My Project->Select Project
3. Click on Apply / decline for the requested applicants.

Actual Result: There is a misalignment of ACCEPT DECLINE buttons. Please see screenshot for more details.
![pasted image at 2017_07_17 04_42 pm](https://user-images.githubusercontent.com/29553195/28289319-2538219a-6b10-11e7-92a0-7c33969ae4d8.png)

**Comment by Code4SocialGood** [comment]
To recreate this issue in DEV (http://dev.code4socialgood.org/)
- Login as nonprofit user:  testnonprofituser2@gmail.com / Opensource5social!
- From drop down, click My Projects
- Click project: Newsletter writer/Editor

Please make the two buttons either vertical align, or horizontal align. You might need to make the buttons narrower or shorter to fit into the space.

![image](https://user-images.githubusercontent.com/24813620/28303256-c9fa0daa-6b57-11e7-81e1-1a89771f6745.png)

**Comment by Code4SocialGood** [comment]
Resolved in PR #846
