### ISSUE TITLE
Project Link URL notification is not correct || Env: Stage

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-web#832]
1. Login as a Volunteer User: StageVolunteerUser@gmail.com   Mycode@11
2. Apply for a project.
3. Verify Email notification
Actual Result: 
The project details URL is not correct in the email. Please check screenshot for more details.
![emailurl](https://user-images.githubusercontent.com/29553195/28289668-822aba56-6b11-11e7-9e57-8c9f31244c36.jpg)

**Comment by Code4SocialGood** [comment]
@p-tal This is resolved. please re-test

**Comment by p-tal** [comment]
Retest successful. Defect OK to Close
