### ISSUE TITLE
Volunteer user can see APPLY button on projects that are being Declined before || Env : Stage

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-web#833]
Environment Stage
Browser: Chrome
1. Login using volunteer user: StageVolunteerUser@gmail.com
Mycode@11
2. Apply for project.
3. Login as NonProfit User and DECLINE the user application.
4. Login Back as Volunteer user and Goto Project page.
5. Click on the project you have been declined.

Actual Result: The Volunteer user can see the APPLY button in project page but when clicked on it , "Record already exists" error is thrown.

Expected Result: Once user applied to a project, he will not be able to see APPLY button any more, whether his application status is applied, accepted, or declined

**Comment by Code4SocialGood** [comment]
Code change request:
In Project View Page, Disable the Apply button if:
- the user is volunteer, and 
- user_project exist and status is A (Applied), or C (Approved), or D (Declined)

To Recreate this issue in DEV (http://dev.code4socialgood.org/):
1. Open a browser
2. Login as nonprofit user:  testnonprofituser2@gmail.com / Opensource5social!
3. From drop down, click My Projects

4. Open another browser
5. Login as volunteer user: testvolunteeruser2@gmail.com / Opensource5social!
6. Click projects
7. Click a project that is on the nonprofit's My Projects list
8. Click Apply

9. Go back to nonprofit browser, click the project under My Projects, approve the volunteer

10. Refresh the volunteer browser. The Apply button should be disabled.

**Comment by Code4SocialGood** [comment]
@p-tal Couldn't recreate the issue. Please retest.

**Comment by p-tal** [comment]
apply button is disabled. defect ok to close
