### ISSUE TITLE
Volunteer User can APPLY for project without setting up mandatory profile || Env Stage

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-web#836]
1.Login as a new volunteer user.
2. Go to Project Page.
3. Select a project available and click on Apply.

Actual Result: User is able to apply for project.

Expected Result: User should be prompted to complete his/her profile setting in My settings page.

**Comment by Code4SocialGood** [comment]
**Code Change Request**

In Project View Page, Disable the Apply button if:
- The user is volunteer, and
- User status is 'N' (new user, not active yet)

Also, add tooltip to indicate the reason button is disabled: "Please complete user settings before apply for a project".

**To recreate this issue in DEV (http://dev.code4socialgood.org/)**
1. Register as a new volunteer user
2. Login
3. Click Projects
4. Click a project
5. Apply button should be disabled, and showing tooltip: "Please complete user settings before apply for a project"

**Comment by Code4SocialGood** [comment]
The issue is fixed. Please retest.

**Comment by p-tal** [comment]
retest successful. defect ok to close
