### ISSUE TITLE
Create Project Page - Image of Project

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#84]
- **Web Path** 
Home Page -> FakeLogin -> Create Project

- **Requirement**
1. User click Upload button to upload image from local file system
2. Image is saved to backend upon upload

- **TBD**
If the project hasn't been created, we won't have project ID. We can't save the image. How to handle this use case?

**Comment by dv4quadcore** [comment]
For this use case for issues #84 and #85, we can have the image displayed upon upload as per usual -- but instead of saving the image immediately, it can be saved when the user clicks on the `Create` button.

**Comment by Code4SocialGood** [comment]
agreed

**Comment by Code4SocialGood** [comment]
Create Project page is to be deleted
