### ISSUE TITLE
Skills in search panel

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#850]
In staging, there are 3 skill tags for projects (testing, java, .net), but only one skill is shown in search panel (test). And they don's match.

Please verify this is a defect.

![image](https://user-images.githubusercontent.com/24813620/28347558-69bb257c-6bfd-11e7-93a4-2e5a5e00f86e.png)

**Comment by p-tal** [comment]
Yes, this is a defect in stage.

**Comment by Code4SocialGood** [comment]
@p-tal Issue is resolved, please retest.
