### ISSUE TITLE
Create Project->Unable to upload image|| Env: Dev and Stage

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-web#856]
1. Login as organization user.
2. Create a project.
3. Upload Image.

Actual Result: Image is not getting uploaded.

**Comment by Code4SocialGood** [comment]
@p-tal Issue is resolved with policy change on uploading image to S3. Please retest.

**Comment by p-tal** [comment]
Retest successful. Defect OK to close
