### ISSUE TITLE
New User not able to goto My Organization page ||Env Stage

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-web#917]
Login as a new Organization user. 
Go to My Settings->My Organization.

Actual Result: My organization page doesn't open.
![myorg](https://user-images.githubusercontent.com/29553195/28641220-764989c6-721c-11e7-9df8-deba4d0ec1fb.jpg)

**Comment by Code4SocialGood** [comment]
Duplicate issue with #915, close this one.
