### ISSUE TITLE
View Organization Page

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#927]
Click Organizations
Click an organization

On the right side panel:
1. If the organization own has no avatar, it should display the default avatar
2. If there is no project posted by the organization, the bottom border is missing
3. Replace the following labels with icons: Name, Title, Phone, Email

![image](https://user-images.githubusercontent.com/24813620/28649318-a5083ab0-7239-11e7-97bd-6c64054918f2.png)

**Comment by Code4SocialGood** [comment]
It seems the icons have various width, so that the values next to icons are not vertically aligned. 

Could  you make change so that:
1. The values next to icons are left aligned
2. Give a bit space between icon and label. The space between the person icon and the person name is good.

![image](https://user-images.githubusercontent.com/24813620/28858558-fce8e662-7716-11e7-9386-2c325e6085f7.png)

**Comment by chaitanyas16** [comment]
Can you confirm if it is fine now,The email is not fitting the right col do I increase the width of the right col?


![rightcol](https://user-images.githubusercontent.com/16686360/28887400-aad8fc10-7782-11e7-8574-77af2d8496f1.png)

**Comment by Code4SocialGood** [comment]
Resolved in PR #1013
