### ISSUE TITLE
Google Map - Display users

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#930]
Current, our google map shows volunteer/organization/admin user, with any user status.

![image](https://user-images.githubusercontent.com/24813620/28749465-cc920862-748d-11e7-8d0e-900f324ba6b1.png)

Please change the logic to only show:
1. Active Volunteer User, with publish_flag = Y
- Display First Name Last Name instead of username
- Make the white space on left side and right side of the popup the same. Currently right side has more white space

2. Active Volunteer User, with publish_flag = N
- In the popup, display default avatar
- For the user name line, display "Anonymous User"
- Display user's State and Country

**Comment by chaitanyas16** [comment]
@Code4SocialGood Can you confirm if the spacing and the content are fine in the screen shots below.

![image](https://user-images.githubusercontent.com/16686360/29042404-67f94618-7b7c-11e7-87b6-db8809bb1901.png)

![image](https://user-images.githubusercontent.com/16686360/29042465-99071b68-7b7c-11e7-85be-c7d8c7631d69.png)

**Comment by Code4SocialGood** [comment]
@chaitanyas16 Sorry, I missed this comment. yes, the spacing and content is fine.
