### ISSUE TITLE
SAVE functionality doesnot work in My organization for longer strings

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-web#960]
1.Login as a Organization user.
2. Go to My organization-> fill in the details with long string in organization description.
3. Hit save.

Actual result: the organization details are not saved. please see screenshot for more details.
![myorg save](https://user-images.githubusercontent.com/29553195/28731727-066b09da-73a3-11e7-8ff0-520be0ff1e77.jpg)

**Comment by Code4SocialGood** [comment]
On frontend, max length is restricted to 1000 char.
However, on backend, max length is restricted to 500 char.
Error will throw if the length of the field exceeds 500 char.

Backend is fixed with PR #331 to accommodate 1000 char.
