### ISSUE TITLE
Home Page - Call to Action

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#968]
Scroll down on home page, please:
- replace the search button to register button
- Login to Post Projects: Change to **Register** to Post Projects. Make the font looks better.
- When user clicks the register button, pop up Auth0 window

![image](https://user-images.githubusercontent.com/24813620/28745425-e9b172fc-743d-11e7-9e6a-23dc93e22bc0.png)

**Comment by webdev-burd** [comment]
I was able to implement the Call to Action button in the second half, but i don't know how to check if a user is logged in, so I won't be able to implement the "Create Project".

**Comment by Code4SocialGood** [comment]
Resolved in PR#992
