### ISSUE TITLE
AYS Model - Change color from green to orange

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#976]
Find modals in the application. Change the color from green to orange, the same orange used for toast.

- **To Test** 
Login as organization user.
Click My Projects
Click an active project
Click DELETE
The modal should display.

![image](https://user-images.githubusercontent.com/24813620/28749769-1f4ed080-7498-11e7-93b1-80bcca8aa1eb.png)

**Comment by webdev-burd** [comment]
The projects on "My Projects" are not loaded, for some reason.
![image](https://user-images.githubusercontent.com/26790341/28753204-5fb04236-7528-11e7-8699-3b3b7945d5db.png)

**Comment by Code4SocialGood** [comment]
I logged in as nonprofit user
Here is what I can see:

**Comment by Code4SocialGood** [comment]
Resolved in PR #989

**Comment by Code4SocialGood** [comment]
@webdev-burd Can we make the text as white color on top of orange background?

![image](https://user-images.githubusercontent.com/24813620/28857327-54ae51ec-770e-11e7-9435-617c617c073e.png)
