### ISSUE TITLE
Organization User - add border

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#980]
Login as organization user: testnonprofituser2@gmail.com / Opensource5social!
Click My Settings
Click Save
On the right side panel, when there is no project posted by the organization, the border on the bottom  is missing. Please add.

![image](https://user-images.githubusercontent.com/24813620/28754694-6168a522-7510-11e7-93cd-f9b6530db6e6.png)

**Comment by axlemax** [comment]
Is this still an issue after PR #985 ?

**Comment by Code4SocialGood** [comment]
Resolved in PR #985
