### ISSUE TITLE
C4SG forum on discourse: Display C4SG's header

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#99]
Reference: https://forum.freecodecamp.com/

**Comment by russon77** [comment]
@Code4SocialGood could you specify exactly what content (and what header)?

**Comment by Code4SocialGood** [comment]
- **Header: AS-IS**

![image](https://cloud.githubusercontent.com/assets/24813620/24134076/cf2b7bd2-0dcf-11e7-8951-eeb8d68918e7.png)

- **Header: TO-BE**

![image](https://cloud.githubusercontent.com/assets/24813620/24134138/25ee011a-0dd0-11e7-93d6-78b9f4cf39fb.png)

- **Content: AS-IS**
Welcome to Discourse
The first paragraph of this pinned topic will be visible as a welcome message to all new visitors on your homepage. It's important! Edit this into a brief description of your community: Who is it for? What can they …

- **Content: TO-BE**
Welcome to the Code for Social Good message boards!

- **All Categories: AS-IS**
Uncategorized
Site Feedback

- **All Categories: TO-BE**
General

**Comment by Code4SocialGood** [comment]
Resolved in PR #950
